/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author simon
 */
public class asignarNota extends javax.swing.JFrame {

    /**
     * Creates new form asignarNota
     */
    public asignarNota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondoAsignarNota = new javax.swing.JPanel();
        jPanelEncabezadoAsignarNota = new javax.swing.JPanel();
        jLabelTituloAsignarNota = new javax.swing.JLabel();
        jSeparator0130 = new javax.swing.JSeparator();
        jSeparator0131 = new javax.swing.JSeparator();
        jLabelMiniSiaAsignarrNota = new javax.swing.JLabel();
        jPanelPiePAginaInscribirNota = new javax.swing.JPanel();
        jButtonSalirAsignarNota = new javax.swing.JButton();
        jButtonVolverAsignarNota = new javax.swing.JButton();
        jTextField0130 = new javax.swing.JTextField();
        jLabelNumGrupAsignarNota = new javax.swing.JLabel();
        jTextField0131 = new javax.swing.JTextField();
        jLabelEstudianteAsignarNota = new javax.swing.JLabel();
        jLabelNotaAsignarNota = new javax.swing.JLabel();
        jTextField0132 = new javax.swing.JTextField();
        jButtonBuscarAsignarNota = new javax.swing.JButton();
        jButtonAsignarAsignarNota = new javax.swing.JButton();
        jLabelComprobanteAsignarNota = new javax.swing.JLabel();
        jTextField0133 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondoAsignarNota.setBackground(new java.awt.Color(205, 237, 246));
        jPanelFondoAsignarNota.setPreferredSize(new java.awt.Dimension(410, 310));

        jPanelEncabezadoAsignarNota.setBackground(new java.awt.Color(239, 123, 69));

        jLabelTituloAsignarNota.setFont(new java.awt.Font("Sylfaen", 3, 20)); // NOI18N
        jLabelTituloAsignarNota.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloAsignarNota.setText("ASIGNAR NOTA");

        jSeparator0131.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelMiniSiaAsignarrNota.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabelMiniSiaAsignarrNota.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMiniSiaAsignarrNota.setText("MiniSia");

        javax.swing.GroupLayout jPanelEncabezadoAsignarNotaLayout = new javax.swing.GroupLayout(jPanelEncabezadoAsignarNota);
        jPanelEncabezadoAsignarNota.setLayout(jPanelEncabezadoAsignarNotaLayout);
        jPanelEncabezadoAsignarNotaLayout.setHorizontalGroup(
            jPanelEncabezadoAsignarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoAsignarNotaLayout.createSequentialGroup()
                .addGroup(jPanelEncabezadoAsignarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator0130, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEncabezadoAsignarNotaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTituloAsignarNota)))
                .addGap(15, 15, 15)
                .addComponent(jSeparator0131, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMiniSiaAsignarrNota)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEncabezadoAsignarNotaLayout.setVerticalGroup(
            jPanelEncabezadoAsignarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator0131)
            .addGroup(jPanelEncabezadoAsignarNotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEncabezadoAsignarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEncabezadoAsignarNotaLayout.createSequentialGroup()
                        .addComponent(jLabelTituloAsignarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator0130, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelMiniSiaAsignarrNota))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPiePAginaInscribirNota.setBackground(new java.awt.Color(239, 123, 69));

        jButtonSalirAsignarNota.setText("SALIR");

        jButtonVolverAsignarNota.setText("VOLVER");
        jButtonVolverAsignarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAsignarNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPiePAginaInscribirNotaLayout = new javax.swing.GroupLayout(jPanelPiePAginaInscribirNota);
        jPanelPiePAginaInscribirNota.setLayout(jPanelPiePAginaInscribirNotaLayout);
        jPanelPiePAginaInscribirNotaLayout.setHorizontalGroup(
            jPanelPiePAginaInscribirNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePAginaInscribirNotaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolverAsignarNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalirAsignarNota)
                .addContainerGap())
        );
        jPanelPiePAginaInscribirNotaLayout.setVerticalGroup(
            jPanelPiePAginaInscribirNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPiePAginaInscribirNotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPiePAginaInscribirNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalirAsignarNota)
                    .addComponent(jButtonVolverAsignarNota))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTextField0130.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField0130ActionPerformed(evt);
            }
        });

        jLabelNumGrupAsignarNota.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelNumGrupAsignarNota.setText("Ingrese el número del grupo");

        jTextField0131.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField0131ActionPerformed(evt);
            }
        });

        jLabelEstudianteAsignarNota.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelEstudianteAsignarNota.setText("Estudiante");

        jLabelNotaAsignarNota.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelNotaAsignarNota.setText("Nota");

        jButtonBuscarAsignarNota.setText("BUSCAR");
        jButtonBuscarAsignarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAsignarNotaActionPerformed(evt);
            }
        });

        jButtonAsignarAsignarNota.setText("ASIGNAR");
        jButtonAsignarAsignarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarAsignarNotaActionPerformed(evt);
            }
        });

        jLabelComprobanteAsignarNota.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelComprobanteAsignarNota.setText("Comprobante");

        javax.swing.GroupLayout jPanelFondoAsignarNotaLayout = new javax.swing.GroupLayout(jPanelFondoAsignarNota);
        jPanelFondoAsignarNota.setLayout(jPanelFondoAsignarNotaLayout);
        jPanelFondoAsignarNotaLayout.setHorizontalGroup(
            jPanelFondoAsignarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEncabezadoAsignarNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPiePAginaInscribirNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelFondoAsignarNotaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelFondoAsignarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoAsignarNotaLayout.createSequentialGroup()
                        .addComponent(jTextField0133, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFondoAsignarNotaLayout.createSequentialGroup()
                        .addGroup(jPanelFondoAsignarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFondoAsignarNotaLayout.createSequentialGroup()
                                .addGroup(jPanelFondoAsignarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEstudianteAsignarNota)
                                    .addComponent(jTextField0131, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelComprobanteAsignarNota))
                                .addGap(29, 29, 29)
                                .addGroup(jPanelFondoAsignarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField0132, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNotaAsignarNota)))
                            .addComponent(jLabelNumGrupAsignarNota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanelFondoAsignarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField0130, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarAsignarNota)
                            .addComponent(jButtonAsignarAsignarNota))
                        .addGap(21, 21, 21))))
        );
        jPanelFondoAsignarNotaLayout.setVerticalGroup(
            jPanelFondoAsignarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoAsignarNotaLayout.createSequentialGroup()
                .addComponent(jPanelEncabezadoAsignarNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFondoAsignarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField0130, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumGrupAsignarNota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButtonBuscarAsignarNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFondoAsignarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstudianteAsignarNota)
                    .addComponent(jLabelNotaAsignarNota))
                .addGap(9, 9, 9)
                .addGroup(jPanelFondoAsignarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField0131, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField0132, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAsignarAsignarNota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelComprobanteAsignarNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField0133, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPiePAginaInscribirNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelFondoAsignarNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelFondoAsignarNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverAsignarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAsignarNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverAsignarNotaActionPerformed

    private void jTextField0130ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField0130ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField0130ActionPerformed

    private void jTextField0131ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField0131ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField0131ActionPerformed

    private void jButtonBuscarAsignarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAsignarNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarAsignarNotaActionPerformed

    private void jButtonAsignarAsignarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarAsignarNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAsignarAsignarNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(asignarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(asignarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(asignarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(asignarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new asignarNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsignarAsignarNota;
    private javax.swing.JButton jButtonBuscarAsignarNota;
    private javax.swing.JButton jButtonSalirAsignarNota;
    private javax.swing.JButton jButtonVolverAsignarNota;
    private javax.swing.JLabel jLabelComprobanteAsignarNota;
    private javax.swing.JLabel jLabelEstudianteAsignarNota;
    private javax.swing.JLabel jLabelMiniSiaAsignarrNota;
    private javax.swing.JLabel jLabelNotaAsignarNota;
    private javax.swing.JLabel jLabelNumGrupAsignarNota;
    private javax.swing.JLabel jLabelTituloAsignarNota;
    private javax.swing.JPanel jPanelEncabezadoAsignarNota;
    private javax.swing.JPanel jPanelFondoAsignarNota;
    private javax.swing.JPanel jPanelPiePAginaInscribirNota;
    private javax.swing.JSeparator jSeparator0130;
    private javax.swing.JSeparator jSeparator0131;
    private javax.swing.JTextField jTextField0130;
    private javax.swing.JTextField jTextField0131;
    private javax.swing.JTextField jTextField0132;
    private javax.swing.JTextField jTextField0133;
    // End of variables declaration//GEN-END:variables
}
