/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

/**
 *
 * @author Jefferson
 */
public class cambiarClave extends javax.swing.JFrame {

    /** Creates new form cambiarClave */
    public cambiarClave() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondoConsultarNota1 = new javax.swing.JPanel();
        jPanelEncabezadoConsultarNota = new javax.swing.JPanel();
        jLabelTituloConsultarNota = new javax.swing.JLabel();
        jSeparator060 = new javax.swing.JSeparator();
        jSeparator061 = new javax.swing.JSeparator();
        jLabelMiniSiaConsultarNota = new javax.swing.JLabel();
        jPanelPiePaginaConsultarNota = new javax.swing.JPanel();
        jButtonSalirConsultarNota = new javax.swing.JButton();
        jButtonVolverConsultarNota = new javax.swing.JButton();
        jLabelIngresarNombreConsultarNota = new javax.swing.JLabel();
        buttonClaveNueva = new javax.swing.JButton();
        fieldClaveNueva = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondoConsultarNota1.setBackground(new java.awt.Color(205, 237, 246));
        jPanelFondoConsultarNota1.setPreferredSize(new java.awt.Dimension(410, 310));

        jPanelEncabezadoConsultarNota.setBackground(new java.awt.Color(239, 123, 69));
        jPanelEncabezadoConsultarNota.setPreferredSize(new java.awt.Dimension(390, 54));

        jLabelTituloConsultarNota.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabelTituloConsultarNota.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloConsultarNota.setText("CAMBIAR CLAVE");

        jSeparator061.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelMiniSiaConsultarNota.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabelMiniSiaConsultarNota.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMiniSiaConsultarNota.setText("MiniSia");

        org.jdesktop.layout.GroupLayout jPanelEncabezadoConsultarNotaLayout = new org.jdesktop.layout.GroupLayout(jPanelEncabezadoConsultarNota);
        jPanelEncabezadoConsultarNota.setLayout(jPanelEncabezadoConsultarNotaLayout);
        jPanelEncabezadoConsultarNotaLayout.setHorizontalGroup(
            jPanelEncabezadoConsultarNotaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEncabezadoConsultarNotaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelEncabezadoConsultarNotaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator060, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelTituloConsultarNota, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 166, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator061, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelMiniSiaConsultarNota)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelEncabezadoConsultarNotaLayout.setVerticalGroup(
            jPanelEncabezadoConsultarNotaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator061)
            .add(jPanelEncabezadoConsultarNotaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelTituloConsultarNota, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator060, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(4, 4, 4))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelEncabezadoConsultarNotaLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabelMiniSiaConsultarNota)
                .addContainerGap())
        );

        jPanelPiePaginaConsultarNota.setBackground(new java.awt.Color(239, 123, 69));
        jPanelPiePaginaConsultarNota.setPreferredSize(new java.awt.Dimension(142, 47));

        jButtonSalirConsultarNota.setText("SALIR");
        jButtonSalirConsultarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirConsultarNotaActionPerformed(evt);
            }
        });

        jButtonVolverConsultarNota.setText("VOLVER");
        jButtonVolverConsultarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverConsultarNotaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelPiePaginaConsultarNotaLayout = new org.jdesktop.layout.GroupLayout(jPanelPiePaginaConsultarNota);
        jPanelPiePaginaConsultarNota.setLayout(jPanelPiePaginaConsultarNotaLayout);
        jPanelPiePaginaConsultarNotaLayout.setHorizontalGroup(
            jPanelPiePaginaConsultarNotaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPiePaginaConsultarNotaLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonVolverConsultarNota)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButtonSalirConsultarNota)
                .add(18, 18, 18))
        );
        jPanelPiePaginaConsultarNotaLayout.setVerticalGroup(
            jPanelPiePaginaConsultarNotaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPiePaginaConsultarNotaLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .add(jPanelPiePaginaConsultarNotaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonSalirConsultarNota)
                    .add(jButtonVolverConsultarNota))
                .addContainerGap())
        );

        jLabelIngresarNombreConsultarNota.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabelIngresarNombreConsultarNota.setText("Ingrese una clave nueva:");

        buttonClaveNueva.setText("CAMBIAR");
        buttonClaveNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClaveNuevaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelFondoConsultarNota1Layout = new org.jdesktop.layout.GroupLayout(jPanelFondoConsultarNota1);
        jPanelFondoConsultarNota1.setLayout(jPanelFondoConsultarNota1Layout);
        jPanelFondoConsultarNota1Layout.setHorizontalGroup(
            jPanelFondoConsultarNota1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEncabezadoConsultarNota, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .add(jPanelPiePaginaConsultarNota, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .add(jPanelFondoConsultarNota1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelFondoConsultarNota1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelFondoConsultarNota1Layout.createSequentialGroup()
                        .add(fieldClaveNueva, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(35, 35, 35)
                        .add(buttonClaveNueva, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabelIngresarNombreConsultarNota, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanelFondoConsultarNota1Layout.setVerticalGroup(
            jPanelFondoConsultarNota1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFondoConsultarNota1Layout.createSequentialGroup()
                .add(jPanelEncabezadoConsultarNota, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabelIngresarNombreConsultarNota)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelFondoConsultarNota1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fieldClaveNueva, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buttonClaveNueva, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(55, 55, 55)
                .add(jPanelPiePaginaConsultarNota, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFondoConsultarNota1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFondoConsultarNota1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirConsultarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirConsultarNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirConsultarNotaActionPerformed

    private void jButtonVolverConsultarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverConsultarNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverConsultarNotaActionPerformed

    private void buttonClaveNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClaveNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClaveNuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cambiarClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cambiarClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cambiarClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cambiarClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cambiarClave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClaveNueva;
    private javax.swing.JTextField fieldClaveNueva;
    private javax.swing.JButton jButtonSalirConsultarNota;
    private javax.swing.JButton jButtonVolverConsultarNota;
    private javax.swing.JLabel jLabelIngresarNombreConsultarNota;
    private javax.swing.JLabel jLabelMiniSiaConsultarNota;
    private javax.swing.JLabel jLabelTituloConsultarNota;
    private javax.swing.JPanel jPanelEncabezadoConsultarNota;
    private javax.swing.JPanel jPanelFondoConsultarNota1;
    private javax.swing.JPanel jPanelPiePaginaConsultarNota;
    private javax.swing.JSeparator jSeparator060;
    private javax.swing.JSeparator jSeparator061;
    // End of variables declaration//GEN-END:variables

}
