
package UI;

import Logica.prueba2;

public class ConsultarSubsidioFrame extends javax.swing.JFrame {

    public ConsultarSubsidioFrame() {
        initComponents();
        this.setSize(430, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoConsultarSubsidios = new javax.swing.JPanel();
        jPanelEncabezadoConsultarSubsidio = new javax.swing.JPanel();
        jLabelTituloConsultarSubsidio = new javax.swing.JLabel();
        jSeparator040 = new javax.swing.JSeparator();
        jSeparator041 = new javax.swing.JSeparator();
        jLabelMiniSiaConsulSubsidio = new javax.swing.JLabel();
        jPanelPiePaginaConsultarSubsidio = new javax.swing.JPanel();
        jButtonSalirConsulSubsidios = new javax.swing.JButton();
        jButtonVolverConsulSubsidio = new javax.swing.JButton();
        jLabelInfoColSubsidio1 = new javax.swing.JLabel();
        jLabelInfoConsulSubsidio2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAreaSubsidiosEst = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoConsultarSubsidios.setBackground(new java.awt.Color(205, 237, 246));
        fondoConsultarSubsidios.setPreferredSize(new java.awt.Dimension(400, 310));

        jPanelEncabezadoConsultarSubsidio.setBackground(new java.awt.Color(239, 123, 69));
        jPanelEncabezadoConsultarSubsidio.setPreferredSize(new java.awt.Dimension(410, 57));

        jLabelTituloConsultarSubsidio.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabelTituloConsultarSubsidio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloConsultarSubsidio.setText("CONSULTAR SUBSIDIOS");

        jSeparator040.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelMiniSiaConsulSubsidio.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabelMiniSiaConsulSubsidio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMiniSiaConsulSubsidio.setText("MiniSia");

        javax.swing.GroupLayout jPanelEncabezadoConsultarSubsidioLayout = new javax.swing.GroupLayout(jPanelEncabezadoConsultarSubsidio);
        jPanelEncabezadoConsultarSubsidio.setLayout(jPanelEncabezadoConsultarSubsidioLayout);
        jPanelEncabezadoConsultarSubsidioLayout.setHorizontalGroup(
            jPanelEncabezadoConsultarSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoConsultarSubsidioLayout.createSequentialGroup()
                .addGroup(jPanelEncabezadoConsultarSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelEncabezadoConsultarSubsidioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTituloConsultarSubsidio, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator041))
                .addGap(18, 18, 18)
                .addComponent(jSeparator040, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMiniSiaConsulSubsidio, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelEncabezadoConsultarSubsidioLayout.setVerticalGroup(
            jPanelEncabezadoConsultarSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator040)
            .addGroup(jPanelEncabezadoConsultarSubsidioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEncabezadoConsultarSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEncabezadoConsultarSubsidioLayout.createSequentialGroup()
                        .addComponent(jLabelTituloConsultarSubsidio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator041, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelMiniSiaConsulSubsidio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPiePaginaConsultarSubsidio.setBackground(new java.awt.Color(239, 123, 69));
        jPanelPiePaginaConsultarSubsidio.setPreferredSize(new java.awt.Dimension(410, 47));

        jButtonSalirConsulSubsidios.setText("SALIR");
        jButtonSalirConsulSubsidios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirConsulSubsidiosActionPerformed(evt);
            }
        });

        jButtonVolverConsulSubsidio.setText("VOLVER");
        jButtonVolverConsulSubsidio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverConsulSubsidioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPiePaginaConsultarSubsidioLayout = new javax.swing.GroupLayout(jPanelPiePaginaConsultarSubsidio);
        jPanelPiePaginaConsultarSubsidio.setLayout(jPanelPiePaginaConsultarSubsidioLayout);
        jPanelPiePaginaConsultarSubsidioLayout.setHorizontalGroup(
            jPanelPiePaginaConsultarSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarSubsidioLayout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(jButtonVolverConsulSubsidio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalirConsulSubsidios)
                .addContainerGap())
        );
        jPanelPiePaginaConsultarSubsidioLayout.setVerticalGroup(
            jPanelPiePaginaConsultarSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPiePaginaConsultarSubsidioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPiePaginaConsultarSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalirConsulSubsidios)
                    .addComponent(jButtonVolverConsulSubsidio))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabelInfoColSubsidio1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelInfoColSubsidio1.setText("A continuación aparecerán los subsidios ");

        jLabelInfoConsulSubsidio2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelInfoConsulSubsidio2.setText("de los cuales es beneficiario:");

        jAreaSubsidiosEst.setColumns(20);
        jAreaSubsidiosEst.setRows(5);
        jScrollPane1.setViewportView(jAreaSubsidiosEst);

        javax.swing.GroupLayout fondoConsultarSubsidiosLayout = new javax.swing.GroupLayout(fondoConsultarSubsidios);
        fondoConsultarSubsidios.setLayout(fondoConsultarSubsidiosLayout);
        fondoConsultarSubsidiosLayout.setHorizontalGroup(
            fondoConsultarSubsidiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoConsultarSubsidiosLayout.createSequentialGroup()
                .addGroup(fondoConsultarSubsidiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEncabezadoConsultarSubsidio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPiePaginaConsultarSubsidio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(fondoConsultarSubsidiosLayout.createSequentialGroup()
                .addGroup(fondoConsultarSubsidiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoConsultarSubsidiosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fondoConsultarSubsidiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInfoColSubsidio1)
                            .addComponent(jLabelInfoConsulSubsidio2)))
                    .addGroup(fondoConsultarSubsidiosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoConsultarSubsidiosLayout.setVerticalGroup(
            fondoConsultarSubsidiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoConsultarSubsidiosLayout.createSequentialGroup()
                .addComponent(jPanelEncabezadoConsultarSubsidio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelInfoColSubsidio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInfoConsulSubsidio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jPanelPiePaginaConsultarSubsidio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(fondoConsultarSubsidios, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverConsulSubsidioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverConsulSubsidioActionPerformed
        // TODO add your handling code here:
        prueba2.CrearInterfazEst();
        this.dispose();
    }//GEN-LAST:event_jButtonVolverConsulSubsidioActionPerformed

    private void jButtonSalirConsulSubsidiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirConsulSubsidiosActionPerformed
        // TODO add your handling code here:
        LoginMain.usuarioActual.remove(0);
        prueba2.CrearLogin();
        this.dispose();
    }//GEN-LAST:event_jButtonSalirConsulSubsidiosActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarSubsidioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarSubsidioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarSubsidioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarSubsidioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarSubsidioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondoConsultarSubsidios;
    public javax.swing.JTextArea jAreaSubsidiosEst;
    private javax.swing.JButton jButtonSalirConsulSubsidios;
    private javax.swing.JButton jButtonVolverConsulSubsidio;
    private javax.swing.JLabel jLabelInfoColSubsidio1;
    private javax.swing.JLabel jLabelInfoConsulSubsidio2;
    private javax.swing.JLabel jLabelMiniSiaConsulSubsidio;
    private javax.swing.JLabel jLabelTituloConsultarSubsidio;
    private javax.swing.JPanel jPanelEncabezadoConsultarSubsidio;
    private javax.swing.JPanel jPanelPiePaginaConsultarSubsidio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator040;
    private javax.swing.JSeparator jSeparator041;
    // End of variables declaration//GEN-END:variables
}
