/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author simon
 */
public class iInscribirMaterias extends javax.swing.JFrame {

    /**
     * Creates new form iInscribirMaterias
     */
    public iInscribirMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondoInscribirMat = new javax.swing.JPanel();
        jPanelEncabezadoInscribirMat = new javax.swing.JPanel();
        jLabelTituloInscribirMat = new javax.swing.JLabel();
        jSeparator0100 = new javax.swing.JSeparator();
        jSeparator0101 = new javax.swing.JSeparator();
        jLabelMiniSIaInscribirMat = new javax.swing.JLabel();
        jPanelPiePaginaInscribirMat = new javax.swing.JPanel();
        jButtonSalirInscribirMat = new javax.swing.JButton();
        jButtonVolverInscribirMat = new javax.swing.JButton();
        jComboBoxInscribirMat = new javax.swing.JComboBox<>();
        jButtonInscribirInscribirMat = new javax.swing.JButton();
        jLabelInstruc1InscribirMat = new javax.swing.JLabel();
        jLabelInstruct2InscribirMat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondoInscribirMat.setBackground(new java.awt.Color(205, 237, 246));

        jPanelEncabezadoInscribirMat.setBackground(new java.awt.Color(239, 123, 69));

        jLabelTituloInscribirMat.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabelTituloInscribirMat.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloInscribirMat.setText("INSCRIBIR MATERIAS");

        jSeparator0101.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelMiniSIaInscribirMat.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabelMiniSIaInscribirMat.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMiniSIaInscribirMat.setText("MiniSia");

        javax.swing.GroupLayout jPanelEncabezadoInscribirMatLayout = new javax.swing.GroupLayout(jPanelEncabezadoInscribirMat);
        jPanelEncabezadoInscribirMat.setLayout(jPanelEncabezadoInscribirMatLayout);
        jPanelEncabezadoInscribirMatLayout.setHorizontalGroup(
            jPanelEncabezadoInscribirMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoInscribirMatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEncabezadoInscribirMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloInscribirMat, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator0100, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator0101, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMiniSIaInscribirMat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEncabezadoInscribirMatLayout.setVerticalGroup(
            jPanelEncabezadoInscribirMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator0101, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelEncabezadoInscribirMatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEncabezadoInscribirMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEncabezadoInscribirMatLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jLabelTituloInscribirMat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator0100, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEncabezadoInscribirMatLayout.createSequentialGroup()
                        .addComponent(jLabelMiniSIaInscribirMat)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanelPiePaginaInscribirMat.setBackground(new java.awt.Color(239, 123, 69));

        jButtonSalirInscribirMat.setText("SALIR");
        jButtonSalirInscribirMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirInscribirMatActionPerformed(evt);
            }
        });

        jButtonVolverInscribirMat.setText("VOLVER");

        javax.swing.GroupLayout jPanelPiePaginaInscribirMatLayout = new javax.swing.GroupLayout(jPanelPiePaginaInscribirMat);
        jPanelPiePaginaInscribirMat.setLayout(jPanelPiePaginaInscribirMatLayout);
        jPanelPiePaginaInscribirMatLayout.setHorizontalGroup(
            jPanelPiePaginaInscribirMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaInscribirMatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolverInscribirMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalirInscribirMat)
                .addGap(13, 13, 13))
        );
        jPanelPiePaginaInscribirMatLayout.setVerticalGroup(
            jPanelPiePaginaInscribirMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaInscribirMatLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanelPiePaginaInscribirMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalirInscribirMat)
                    .addComponent(jButtonVolverInscribirMat))
                .addContainerGap())
        );

        jComboBoxInscribirMat.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jComboBoxInscribirMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonInscribirInscribirMat.setText("INSCRIBIR");
        jButtonInscribirInscribirMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscribirInscribirMatActionPerformed(evt);
            }
        });

        jLabelInstruc1InscribirMat.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabelInstruc1InscribirMat.setText("Seleccione una materia y luego pulse \"INSCRIBIR\"");

        jLabelInstruct2InscribirMat.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabelInstruct2InscribirMat.setText(" para añadirla en sus materias inscritas");

        javax.swing.GroupLayout jPanelFondoInscribirMatLayout = new javax.swing.GroupLayout(jPanelFondoInscribirMat);
        jPanelFondoInscribirMat.setLayout(jPanelFondoInscribirMatLayout);
        jPanelFondoInscribirMatLayout.setHorizontalGroup(
            jPanelFondoInscribirMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEncabezadoInscribirMat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPiePaginaInscribirMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelFondoInscribirMatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFondoInscribirMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoInscribirMatLayout.createSequentialGroup()
                        .addComponent(jComboBoxInscribirMat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonInscribirInscribirMat))
                    .addComponent(jLabelInstruc1InscribirMat, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInstruct2InscribirMat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFondoInscribirMatLayout.setVerticalGroup(
            jPanelFondoInscribirMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoInscribirMatLayout.createSequentialGroup()
                .addComponent(jPanelEncabezadoInscribirMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabelInstruc1InscribirMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelInstruct2InscribirMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanelFondoInscribirMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxInscribirMat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInscribirInscribirMat))
                .addGap(70, 70, 70)
                .addComponent(jPanelPiePaginaInscribirMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelFondoInscribirMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelFondoInscribirMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirInscribirMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirInscribirMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirInscribirMatActionPerformed

    private void jButtonInscribirInscribirMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscribirInscribirMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInscribirInscribirMatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iInscribirMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iInscribirMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iInscribirMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iInscribirMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iInscribirMaterias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInscribirInscribirMat;
    private javax.swing.JButton jButtonSalirInscribirMat;
    private javax.swing.JButton jButtonVolverInscribirMat;
    private javax.swing.JComboBox<String> jComboBoxInscribirMat;
    private javax.swing.JLabel jLabelInstruc1InscribirMat;
    private javax.swing.JLabel jLabelInstruct2InscribirMat;
    private javax.swing.JLabel jLabelMiniSIaInscribirMat;
    private javax.swing.JLabel jLabelTituloInscribirMat;
    private javax.swing.JPanel jPanelEncabezadoInscribirMat;
    private javax.swing.JPanel jPanelFondoInscribirMat;
    private javax.swing.JPanel jPanelPiePaginaInscribirMat;
    private javax.swing.JSeparator jSeparator0100;
    private javax.swing.JSeparator jSeparator0101;
    // End of variables declaration//GEN-END:variables
}
