/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

/**
 *
 * @author Jefferson
 */
public class infoPersonal extends javax.swing.JFrame {

    /** Creates new form infoPersonal */
    public infoPersonal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondoConsultarNota = new javax.swing.JPanel();
        jPanelEncabezadoConsultarNota1 = new javax.swing.JPanel();
        jLabelTituloConsultarNota1 = new javax.swing.JLabel();
        jSeparator61 = new javax.swing.JSeparator();
        jSeparator62 = new javax.swing.JSeparator();
        jLabelMiniSiaConsultarNota1 = new javax.swing.JLabel();
        jPanelPiePaginaConsultarNota1 = new javax.swing.JPanel();
        jButtonSalirConsultarNota1 = new javax.swing.JButton();
        jButtonVolverConsultarNota1 = new javax.swing.JButton();
        jLabelIngresarNombreConsultarNota1 = new javax.swing.JLabel();
        campoInfopersonal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondoConsultarNota.setBackground(new java.awt.Color(205, 237, 246));
        jPanelFondoConsultarNota.setPreferredSize(new java.awt.Dimension(410, 310));

        jPanelEncabezadoConsultarNota1.setBackground(new java.awt.Color(239, 123, 69));
        jPanelEncabezadoConsultarNota1.setPreferredSize(new java.awt.Dimension(390, 54));

        jLabelTituloConsultarNota1.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabelTituloConsultarNota1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloConsultarNota1.setText("CONSULTAR INFORMACIÓN ");

        jSeparator62.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelMiniSiaConsultarNota1.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabelMiniSiaConsultarNota1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMiniSiaConsultarNota1.setText("MiniSia");

        org.jdesktop.layout.GroupLayout jPanelEncabezadoConsultarNota1Layout = new org.jdesktop.layout.GroupLayout(jPanelEncabezadoConsultarNota1);
        jPanelEncabezadoConsultarNota1.setLayout(jPanelEncabezadoConsultarNota1Layout);
        jPanelEncabezadoConsultarNota1Layout.setHorizontalGroup(
            jPanelEncabezadoConsultarNota1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEncabezadoConsultarNota1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelEncabezadoConsultarNota1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelTituloConsultarNota1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelMiniSiaConsultarNota1)
                .add(27, 27, 27))
        );
        jPanelEncabezadoConsultarNota1Layout.setVerticalGroup(
            jPanelEncabezadoConsultarNota1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator62)
            .add(jPanelEncabezadoConsultarNota1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelTituloConsultarNota1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(4, 4, 4))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelEncabezadoConsultarNota1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabelMiniSiaConsultarNota1)
                .addContainerGap())
        );

        jPanelPiePaginaConsultarNota1.setBackground(new java.awt.Color(239, 123, 69));
        jPanelPiePaginaConsultarNota1.setPreferredSize(new java.awt.Dimension(142, 47));

        jButtonSalirConsultarNota1.setText("SALIR");
        jButtonSalirConsultarNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirConsultarNota1ActionPerformed(evt);
            }
        });

        jButtonVolverConsultarNota1.setText("VOLVER");
        jButtonVolverConsultarNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverConsultarNota1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelPiePaginaConsultarNota1Layout = new org.jdesktop.layout.GroupLayout(jPanelPiePaginaConsultarNota1);
        jPanelPiePaginaConsultarNota1.setLayout(jPanelPiePaginaConsultarNota1Layout);
        jPanelPiePaginaConsultarNota1Layout.setHorizontalGroup(
            jPanelPiePaginaConsultarNota1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPiePaginaConsultarNota1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonVolverConsultarNota1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButtonSalirConsultarNota1)
                .add(18, 18, 18))
        );
        jPanelPiePaginaConsultarNota1Layout.setVerticalGroup(
            jPanelPiePaginaConsultarNota1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPiePaginaConsultarNota1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .add(jPanelPiePaginaConsultarNota1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonSalirConsultarNota1)
                    .add(jButtonVolverConsultarNota1))
                .addContainerGap())
        );

        jLabelIngresarNombreConsultarNota1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabelIngresarNombreConsultarNota1.setText("Esto es lo que el sistema sabe de ti:");

        org.jdesktop.layout.GroupLayout jPanelFondoConsultarNotaLayout = new org.jdesktop.layout.GroupLayout(jPanelFondoConsultarNota);
        jPanelFondoConsultarNota.setLayout(jPanelFondoConsultarNotaLayout);
        jPanelFondoConsultarNotaLayout.setHorizontalGroup(
            jPanelFondoConsultarNotaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEncabezadoConsultarNota1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .add(jPanelPiePaginaConsultarNota1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .add(jPanelFondoConsultarNotaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelIngresarNombreConsultarNota1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFondoConsultarNotaLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(campoInfopersonal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 287, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(54, 54, 54))
        );
        jPanelFondoConsultarNotaLayout.setVerticalGroup(
            jPanelFondoConsultarNotaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFondoConsultarNotaLayout.createSequentialGroup()
                .add(jPanelEncabezadoConsultarNota1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabelIngresarNombreConsultarNota1)
                .add(11, 11, 11)
                .add(campoInfopersonal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(jPanelPiePaginaConsultarNota1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFondoConsultarNota, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jPanelFondoConsultarNota, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirConsultarNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirConsultarNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirConsultarNota1ActionPerformed

    private void jButtonVolverConsultarNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverConsultarNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverConsultarNota1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infoPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoInfopersonal;
    private javax.swing.JButton jButtonSalirConsultarNota1;
    private javax.swing.JButton jButtonVolverConsultarNota1;
    private javax.swing.JLabel jLabelIngresarNombreConsultarNota1;
    private javax.swing.JLabel jLabelMiniSiaConsultarNota1;
    private javax.swing.JLabel jLabelTituloConsultarNota1;
    private javax.swing.JPanel jPanelEncabezadoConsultarNota1;
    private javax.swing.JPanel jPanelFondoConsultarNota;
    private javax.swing.JPanel jPanelPiePaginaConsultarNota1;
    private javax.swing.JSeparator jSeparator61;
    private javax.swing.JSeparator jSeparator62;
    // End of variables declaration//GEN-END:variables

}
