/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author juan manuel
 */
public class interfazPapito extends javax.swing.JFrame {

    /**
     * Creates new form interfazPapitos
     */
    public interfazPapito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultas1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_consultarNotaPapito = new javax.swing.JButton();
        btn_consultarHorarioPapito = new javax.swing.JButton();
        btn_consultarProfesoresPapito = new javax.swing.JButton();
        btn_consultarInfoPap = new javax.swing.JButton();
        asignacion1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_asgClave1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        mensajeBienvenidaPapito = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consultas1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        consultas1.setForeground(new java.awt.Color(205, 237, 246));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Consultas");

        btn_consultarNotaPapito.setText("Nota");

        btn_consultarHorarioPapito.setText("Horario");
        btn_consultarHorarioPapito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarHorarioPapitoActionPerformed(evt);
            }
        });

        btn_consultarProfesoresPapito.setText("Profesores");

        btn_consultarInfoPap.setText("Info. Personal");
        btn_consultarInfoPap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarInfoPapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultas1Layout = new javax.swing.GroupLayout(consultas1);
        consultas1.setLayout(consultas1Layout);
        consultas1Layout.setHorizontalGroup(
            consultas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_consultarHorarioPapito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_consultarProfesoresPapito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_consultarInfoPap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(consultas1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(110, 110, 110)
                        .addComponent(btn_consultarNotaPapito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        consultas1Layout.setVerticalGroup(
            consultas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultas1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btn_consultarNotaPapito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_consultarHorarioPapito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_consultarProfesoresPapito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_consultarInfoPap)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        asignacion1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        asignacion1.setForeground(new java.awt.Color(205, 237, 246));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Asignaciones");

        btn_asgClave1.setText("Cambiar Clave");

        javax.swing.GroupLayout asignacion1Layout = new javax.swing.GroupLayout(asignacion1);
        asignacion1.setLayout(asignacion1Layout);
        asignacion1Layout.setHorizontalGroup(
            asignacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignacion1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asignacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(btn_asgClave1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        asignacion1Layout.setVerticalGroup(
            asignacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignacion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_asgClave1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(239, 123, 69));

        mensajeBienvenidaPapito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mensajeBienvenidaPapito.setForeground(new java.awt.Color(255, 255, 255));
        mensajeBienvenidaPapito.setText("  ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensajeBienvenidaPapito, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(mensajeBienvenidaPapito)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(239, 123, 69));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(asignacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asignacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_consultarHorarioPapitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarHorarioPapitoActionPerformed
        // TODO add your handling code here:
/*
        interfaz_horario.setAlwaysOnTop(true);
        interfaz_horario.locate(300, 500);
        interfaz_horario.setVisible(true);
        interfaz_horario.setTitle("Horario");
        //mensajeBienvenida.setVisible(false);
        interfaz_horario.setSize(500, 300);
        /*
        Papito consultante = (Papito) pap_actual.get(0);
        ArrayList horario = new ArrayList<String>();
        horario = logica_consultas.consultarHorario(consultante);

        ´Pendiente ver como arreglar esto del horario, para que salga algo xd
        tambien pendiente ver como hacer saltos de linea xd
        */
/*
        label_horarioLunes.setText("El textfield funciona");
  */      
        
    }//GEN-LAST:event_btn_consultarHorarioPapitoActionPerformed

    private void btn_consultarInfoPapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarInfoPapActionPerformed
        // TODO add your handling code here:
        /*
        Papito consultor =  (Papito) pap_actual.get(0);
        //jInternalFrame1.setVisible(false);
        interfaz_info.setAlwaysOnTop(true);
        interfaz_info.locate(300, 500);
        interfaz_info.setVisible(true);
        interfaz_info.setTitle("Informacion Personal");
        //mensajeBienvenida.setVisible(false);
        interfaz_info.setSize(500, 300);
        label_nombre.setText("- Nombre: "+ consultor.getNombre());
        label_id.setText("- ID: "+ consultor.getID());
        label_usuario.setText("- Usuario: "+ consultor.getUsuario());
        */

    }//GEN-LAST:event_btn_consultarInfoPapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazPapito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazPapito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazPapito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazPapito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazPapito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel asignacion1;
    private javax.swing.JButton btn_asgClave1;
    private javax.swing.JButton btn_consultarHorarioPapito;
    private javax.swing.JButton btn_consultarInfoPap;
    private javax.swing.JButton btn_consultarNotaPapito;
    private javax.swing.JButton btn_consultarProfesoresPapito;
    private javax.swing.JPanel consultas1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel mensajeBienvenidaPapito;
    // End of variables declaration//GEN-END:variables
}
