/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

/**
 *
 * @author Jefferson
 */
public class pedirSubsidio extends javax.swing.JFrame {

    /** Creates new form pedirSubsidio */
    public pedirSubsidio() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondoConsultarNota7 = new javax.swing.JPanel();
        jPanelEncabezadoConsultarNota8 = new javax.swing.JPanel();
        jLabelTituloConsultarNota8 = new javax.swing.JLabel();
        jSeparator75 = new javax.swing.JSeparator();
        jSeparator76 = new javax.swing.JSeparator();
        jLabelMiniSiaConsultarNota8 = new javax.swing.JLabel();
        jPanelPiePaginaConsultarNota5 = new javax.swing.JPanel();
        jButtonSalirConsultarNota5 = new javax.swing.JButton();
        jButtonVolverConsultarNota5 = new javax.swing.JButton();
        jLabelIngresarNombreConsultarNota3 = new javax.swing.JLabel();
        jTextField64 = new javax.swing.JTextField();
        jPanelFondoConsultarNota8 = new javax.swing.JPanel();
        jPanelEncabezadoConsultarNota9 = new javax.swing.JPanel();
        jLabelTituloConsultarNota9 = new javax.swing.JLabel();
        jSeparator77 = new javax.swing.JSeparator();
        jSeparator78 = new javax.swing.JSeparator();
        jLabelMiniSiaConsultarNota9 = new javax.swing.JLabel();
        jPanelPiePaginaConsultarNota6 = new javax.swing.JPanel();
        jButtonSalirConsultarNota6 = new javax.swing.JButton();
        jButtonVolverConsultarNota6 = new javax.swing.JButton();
        jLabelIngresarNombreConsultarNota4 = new javax.swing.JLabel();
        jTextField65 = new javax.swing.JTextField();

        jPanelFondoConsultarNota7.setBackground(new java.awt.Color(205, 237, 246));
        jPanelFondoConsultarNota7.setPreferredSize(new java.awt.Dimension(410, 310));

        jPanelEncabezadoConsultarNota8.setBackground(new java.awt.Color(239, 123, 69));
        jPanelEncabezadoConsultarNota8.setPreferredSize(new java.awt.Dimension(390, 54));

        jLabelTituloConsultarNota8.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabelTituloConsultarNota8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloConsultarNota8.setText("PROFESORES");

        jSeparator76.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelMiniSiaConsultarNota8.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabelMiniSiaConsultarNota8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMiniSiaConsultarNota8.setText("MiniSia");

        org.jdesktop.layout.GroupLayout jPanelEncabezadoConsultarNota8Layout = new org.jdesktop.layout.GroupLayout(jPanelEncabezadoConsultarNota8);
        jPanelEncabezadoConsultarNota8.setLayout(jPanelEncabezadoConsultarNota8Layout);
        jPanelEncabezadoConsultarNota8Layout.setHorizontalGroup(
            jPanelEncabezadoConsultarNota8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEncabezadoConsultarNota8Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelEncabezadoConsultarNota8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelTituloConsultarNota8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelMiniSiaConsultarNota8)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelEncabezadoConsultarNota8Layout.setVerticalGroup(
            jPanelEncabezadoConsultarNota8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator76)
            .add(jPanelEncabezadoConsultarNota8Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelTituloConsultarNota8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(4, 4, 4))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelEncabezadoConsultarNota8Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabelMiniSiaConsultarNota8)
                .addContainerGap())
        );

        jPanelPiePaginaConsultarNota5.setBackground(new java.awt.Color(239, 123, 69));
        jPanelPiePaginaConsultarNota5.setPreferredSize(new java.awt.Dimension(142, 47));

        jButtonSalirConsultarNota5.setText("SALIR");
        jButtonSalirConsultarNota5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirConsultarNota5ActionPerformed(evt);
            }
        });

        jButtonVolverConsultarNota5.setText("VOLVER");
        jButtonVolverConsultarNota5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverConsultarNota5ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelPiePaginaConsultarNota5Layout = new org.jdesktop.layout.GroupLayout(jPanelPiePaginaConsultarNota5);
        jPanelPiePaginaConsultarNota5.setLayout(jPanelPiePaginaConsultarNota5Layout);
        jPanelPiePaginaConsultarNota5Layout.setHorizontalGroup(
            jPanelPiePaginaConsultarNota5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPiePaginaConsultarNota5Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonVolverConsultarNota5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButtonSalirConsultarNota5)
                .add(18, 18, 18))
        );
        jPanelPiePaginaConsultarNota5Layout.setVerticalGroup(
            jPanelPiePaginaConsultarNota5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPiePaginaConsultarNota5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .add(jPanelPiePaginaConsultarNota5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonSalirConsultarNota5)
                    .add(jButtonVolverConsultarNota5))
                .addContainerGap())
        );

        jLabelIngresarNombreConsultarNota3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabelIngresarNombreConsultarNota3.setText("Estos son tus profesores:");

        org.jdesktop.layout.GroupLayout jPanelFondoConsultarNota7Layout = new org.jdesktop.layout.GroupLayout(jPanelFondoConsultarNota7);
        jPanelFondoConsultarNota7.setLayout(jPanelFondoConsultarNota7Layout);
        jPanelFondoConsultarNota7Layout.setHorizontalGroup(
            jPanelFondoConsultarNota7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEncabezadoConsultarNota8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .add(jPanelPiePaginaConsultarNota5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .add(jPanelFondoConsultarNota7Layout.createSequentialGroup()
                .add(jPanelFondoConsultarNota7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelFondoConsultarNota7Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabelIngresarNombreConsultarNota3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelFondoConsultarNota7Layout.createSequentialGroup()
                        .add(56, 56, 56)
                        .add(jTextField64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 295, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanelFondoConsultarNota7Layout.setVerticalGroup(
            jPanelFondoConsultarNota7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFondoConsultarNota7Layout.createSequentialGroup()
                .add(jPanelEncabezadoConsultarNota8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabelIngresarNombreConsultarNota3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jTextField64, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(jPanelPiePaginaConsultarNota5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondoConsultarNota8.setBackground(new java.awt.Color(205, 237, 246));
        jPanelFondoConsultarNota8.setPreferredSize(new java.awt.Dimension(410, 310));

        jPanelEncabezadoConsultarNota9.setBackground(new java.awt.Color(239, 123, 69));
        jPanelEncabezadoConsultarNota9.setPreferredSize(new java.awt.Dimension(390, 54));

        jLabelTituloConsultarNota9.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabelTituloConsultarNota9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloConsultarNota9.setText("PEDIR SUBSIDIO");

        jSeparator78.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelMiniSiaConsultarNota9.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabelMiniSiaConsultarNota9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMiniSiaConsultarNota9.setText("MiniSia");

        org.jdesktop.layout.GroupLayout jPanelEncabezadoConsultarNota9Layout = new org.jdesktop.layout.GroupLayout(jPanelEncabezadoConsultarNota9);
        jPanelEncabezadoConsultarNota9.setLayout(jPanelEncabezadoConsultarNota9Layout);
        jPanelEncabezadoConsultarNota9Layout.setHorizontalGroup(
            jPanelEncabezadoConsultarNota9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEncabezadoConsultarNota9Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelEncabezadoConsultarNota9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelTituloConsultarNota9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelMiniSiaConsultarNota9)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelEncabezadoConsultarNota9Layout.setVerticalGroup(
            jPanelEncabezadoConsultarNota9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator78)
            .add(jPanelEncabezadoConsultarNota9Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelTituloConsultarNota9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(4, 4, 4))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelEncabezadoConsultarNota9Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabelMiniSiaConsultarNota9)
                .addContainerGap())
        );

        jPanelPiePaginaConsultarNota6.setBackground(new java.awt.Color(239, 123, 69));
        jPanelPiePaginaConsultarNota6.setPreferredSize(new java.awt.Dimension(142, 47));

        jButtonSalirConsultarNota6.setText("SALIR");
        jButtonSalirConsultarNota6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirConsultarNota6ActionPerformed(evt);
            }
        });

        jButtonVolverConsultarNota6.setText("VOLVER");
        jButtonVolverConsultarNota6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverConsultarNota6ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelPiePaginaConsultarNota6Layout = new org.jdesktop.layout.GroupLayout(jPanelPiePaginaConsultarNota6);
        jPanelPiePaginaConsultarNota6.setLayout(jPanelPiePaginaConsultarNota6Layout);
        jPanelPiePaginaConsultarNota6Layout.setHorizontalGroup(
            jPanelPiePaginaConsultarNota6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPiePaginaConsultarNota6Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonVolverConsultarNota6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButtonSalirConsultarNota6)
                .add(18, 18, 18))
        );
        jPanelPiePaginaConsultarNota6Layout.setVerticalGroup(
            jPanelPiePaginaConsultarNota6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPiePaginaConsultarNota6Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .add(jPanelPiePaginaConsultarNota6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonSalirConsultarNota6)
                    .add(jButtonVolverConsultarNota6))
                .addContainerGap())
        );

        jLabelIngresarNombreConsultarNota4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabelIngresarNombreConsultarNota4.setText("Estos son tus profesores:");

        org.jdesktop.layout.GroupLayout jPanelFondoConsultarNota8Layout = new org.jdesktop.layout.GroupLayout(jPanelFondoConsultarNota8);
        jPanelFondoConsultarNota8.setLayout(jPanelFondoConsultarNota8Layout);
        jPanelFondoConsultarNota8Layout.setHorizontalGroup(
            jPanelFondoConsultarNota8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEncabezadoConsultarNota9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .add(jPanelPiePaginaConsultarNota6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .add(jPanelFondoConsultarNota8Layout.createSequentialGroup()
                .add(jPanelFondoConsultarNota8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelFondoConsultarNota8Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabelIngresarNombreConsultarNota4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelFondoConsultarNota8Layout.createSequentialGroup()
                        .add(56, 56, 56)
                        .add(jTextField65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 295, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanelFondoConsultarNota8Layout.setVerticalGroup(
            jPanelFondoConsultarNota8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFondoConsultarNota8Layout.createSequentialGroup()
                .add(jPanelEncabezadoConsultarNota9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabelIngresarNombreConsultarNota4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jTextField65, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(jPanelPiePaginaConsultarNota6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 410, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanelFondoConsultarNota8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 310, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanelFondoConsultarNota8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirConsultarNota5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirConsultarNota5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirConsultarNota5ActionPerformed

    private void jButtonVolverConsultarNota5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverConsultarNota5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverConsultarNota5ActionPerformed

    private void jButtonSalirConsultarNota6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirConsultarNota6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirConsultarNota6ActionPerformed

    private void jButtonVolverConsultarNota6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverConsultarNota6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverConsultarNota6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pedirSubsidio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pedirSubsidio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pedirSubsidio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pedirSubsidio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pedirSubsidio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalirConsultarNota5;
    private javax.swing.JButton jButtonSalirConsultarNota6;
    private javax.swing.JButton jButtonVolverConsultarNota5;
    private javax.swing.JButton jButtonVolverConsultarNota6;
    private javax.swing.JLabel jLabelIngresarNombreConsultarNota3;
    private javax.swing.JLabel jLabelIngresarNombreConsultarNota4;
    private javax.swing.JLabel jLabelMiniSiaConsultarNota4;
    private javax.swing.JLabel jLabelMiniSiaConsultarNota5;
    private javax.swing.JLabel jLabelMiniSiaConsultarNota6;
    private javax.swing.JLabel jLabelMiniSiaConsultarNota7;
    private javax.swing.JLabel jLabelMiniSiaConsultarNota8;
    private javax.swing.JLabel jLabelMiniSiaConsultarNota9;
    private javax.swing.JLabel jLabelTituloConsultarNota4;
    private javax.swing.JLabel jLabelTituloConsultarNota5;
    private javax.swing.JLabel jLabelTituloConsultarNota6;
    private javax.swing.JLabel jLabelTituloConsultarNota7;
    private javax.swing.JLabel jLabelTituloConsultarNota8;
    private javax.swing.JLabel jLabelTituloConsultarNota9;
    private javax.swing.JPanel jPanelEncabezadoConsultarNota4;
    private javax.swing.JPanel jPanelEncabezadoConsultarNota5;
    private javax.swing.JPanel jPanelEncabezadoConsultarNota6;
    private javax.swing.JPanel jPanelEncabezadoConsultarNota7;
    private javax.swing.JPanel jPanelEncabezadoConsultarNota8;
    private javax.swing.JPanel jPanelEncabezadoConsultarNota9;
    private javax.swing.JPanel jPanelFondoConsultarNota3;
    private javax.swing.JPanel jPanelFondoConsultarNota4;
    private javax.swing.JPanel jPanelFondoConsultarNota5;
    private javax.swing.JPanel jPanelFondoConsultarNota6;
    private javax.swing.JPanel jPanelFondoConsultarNota7;
    private javax.swing.JPanel jPanelFondoConsultarNota8;
    private javax.swing.JPanel jPanelPiePaginaConsultarNota5;
    private javax.swing.JPanel jPanelPiePaginaConsultarNota6;
    private javax.swing.JSeparator jSeparator67;
    private javax.swing.JSeparator jSeparator68;
    private javax.swing.JSeparator jSeparator69;
    private javax.swing.JSeparator jSeparator70;
    private javax.swing.JSeparator jSeparator71;
    private javax.swing.JSeparator jSeparator72;
    private javax.swing.JSeparator jSeparator73;
    private javax.swing.JSeparator jSeparator74;
    private javax.swing.JSeparator jSeparator75;
    private javax.swing.JSeparator jSeparator76;
    private javax.swing.JSeparator jSeparator77;
    private javax.swing.JSeparator jSeparator78;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    // End of variables declaration//GEN-END:variables

}
