/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author juan manuel
 */
public class pedir_subsidio extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public pedir_subsidio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondoConsultarNota8 = new javax.swing.JPanel();
        jPanelEncabezadoConsultarNota9 = new javax.swing.JPanel();
        jLabelTituloConsultarNota9 = new javax.swing.JLabel();
        jSeparator77 = new javax.swing.JSeparator();
        jSeparator78 = new javax.swing.JSeparator();
        jLabelMiniSiaConsultarNota9 = new javax.swing.JLabel();
        jPanelPiePaginaConsultarNota6 = new javax.swing.JPanel();
        jButtonSalirConsultarNota6 = new javax.swing.JButton();
        jButtonVolverConsultarNota6 = new javax.swing.JButton();
        buttonEditarsubsidio = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanelPiePaginaConsultarNota8 = new javax.swing.JPanel();
        jButtonSalirConsultarNota8 = new javax.swing.JButton();
        jButtonVolverConsultarNota9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondoConsultarNota8.setBackground(new java.awt.Color(205, 237, 246));
        jPanelFondoConsultarNota8.setPreferredSize(new java.awt.Dimension(410, 310));

        jPanelEncabezadoConsultarNota9.setBackground(new java.awt.Color(239, 123, 69));
        jPanelEncabezadoConsultarNota9.setPreferredSize(new java.awt.Dimension(390, 54));

        jLabelTituloConsultarNota9.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabelTituloConsultarNota9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloConsultarNota9.setText("PEDIR SUBSIDIO");

        jSeparator78.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelMiniSiaConsultarNota9.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabelMiniSiaConsultarNota9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMiniSiaConsultarNota9.setText("MiniSia");

        javax.swing.GroupLayout jPanelEncabezadoConsultarNota9Layout = new javax.swing.GroupLayout(jPanelEncabezadoConsultarNota9);
        jPanelEncabezadoConsultarNota9.setLayout(jPanelEncabezadoConsultarNota9Layout);
        jPanelEncabezadoConsultarNota9Layout.setHorizontalGroup(
            jPanelEncabezadoConsultarNota9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoConsultarNota9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEncabezadoConsultarNota9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator77, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTituloConsultarNota9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator78, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMiniSiaConsultarNota9)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelEncabezadoConsultarNota9Layout.setVerticalGroup(
            jPanelEncabezadoConsultarNota9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator78, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelEncabezadoConsultarNota9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloConsultarNota9, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator77, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEncabezadoConsultarNota9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMiniSiaConsultarNota9)
                .addContainerGap())
        );

        jPanelPiePaginaConsultarNota6.setBackground(new java.awt.Color(239, 123, 69));
        jPanelPiePaginaConsultarNota6.setPreferredSize(new java.awt.Dimension(142, 47));

        jButtonSalirConsultarNota6.setText("SALIR");
        jButtonSalirConsultarNota6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirConsultarNota6ActionPerformed(evt);
            }
        });

        jButtonVolverConsultarNota6.setText("VOLVER");
        jButtonVolverConsultarNota6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverConsultarNota6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPiePaginaConsultarNota6Layout = new javax.swing.GroupLayout(jPanelPiePaginaConsultarNota6);
        jPanelPiePaginaConsultarNota6.setLayout(jPanelPiePaginaConsultarNota6Layout);
        jPanelPiePaginaConsultarNota6Layout.setHorizontalGroup(
            jPanelPiePaginaConsultarNota6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarNota6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolverConsultarNota6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalirConsultarNota6)
                .addGap(18, 18, 18))
        );
        jPanelPiePaginaConsultarNota6Layout.setVerticalGroup(
            jPanelPiePaginaConsultarNota6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarNota6Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelPiePaginaConsultarNota6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalirConsultarNota6)
                    .addComponent(jButtonVolverConsultarNota6))
                .addContainerGap())
        );

        buttonEditarsubsidio.setText("CONFIRMAR SUBSIDIO");
        buttonEditarsubsidio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarsubsidioActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanelPiePaginaConsultarNota8.setBackground(new java.awt.Color(239, 123, 69));
        jPanelPiePaginaConsultarNota8.setPreferredSize(new java.awt.Dimension(142, 47));

        jButtonSalirConsultarNota8.setText("SALIR");
        jButtonSalirConsultarNota8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirConsultarNota8ActionPerformed(evt);
            }
        });

        jButtonVolverConsultarNota9.setText("VOLVER");
        jButtonVolverConsultarNota9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverConsultarNota9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPiePaginaConsultarNota8Layout = new javax.swing.GroupLayout(jPanelPiePaginaConsultarNota8);
        jPanelPiePaginaConsultarNota8.setLayout(jPanelPiePaginaConsultarNota8Layout);
        jPanelPiePaginaConsultarNota8Layout.setHorizontalGroup(
            jPanelPiePaginaConsultarNota8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarNota8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolverConsultarNota9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalirConsultarNota8)
                .addGap(18, 18, 18))
        );
        jPanelPiePaginaConsultarNota8Layout.setVerticalGroup(
            jPanelPiePaginaConsultarNota8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarNota8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPiePaginaConsultarNota8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalirConsultarNota8)
                    .addComponent(jButtonVolverConsultarNota9))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelFondoConsultarNota8Layout = new javax.swing.GroupLayout(jPanelFondoConsultarNota8);
        jPanelFondoConsultarNota8.setLayout(jPanelFondoConsultarNota8Layout);
        jPanelFondoConsultarNota8Layout.setHorizontalGroup(
            jPanelFondoConsultarNota8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEncabezadoConsultarNota9, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addComponent(jPanelPiePaginaConsultarNota6, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addGroup(jPanelFondoConsultarNota8Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoConsultarNota8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonEditarsubsidio)
                .addGap(36, 36, 36))
            .addComponent(jPanelPiePaginaConsultarNota8, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        jPanelFondoConsultarNota8Layout.setVerticalGroup(
            jPanelFondoConsultarNota8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoConsultarNota8Layout.createSequentialGroup()
                .addComponent(jPanelEncabezadoConsultarNota9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanelFondoConsultarNota8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(buttonEditarsubsidio)
                .addGap(31, 31, 31)
                .addComponent(jPanelPiePaginaConsultarNota8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(jPanelPiePaginaConsultarNota6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoConsultarNota8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoConsultarNota8, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirConsultarNota6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirConsultarNota6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirConsultarNota6ActionPerformed

    private void jButtonVolverConsultarNota6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverConsultarNota6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverConsultarNota6ActionPerformed

    private void buttonEditarsubsidioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarsubsidioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditarsubsidioActionPerformed

    private void jButtonSalirConsultarNota8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirConsultarNota8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirConsultarNota8ActionPerformed

    private void jButtonVolverConsultarNota9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverConsultarNota9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverConsultarNota9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pedir_subsidio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pedir_subsidio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pedir_subsidio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pedir_subsidio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pedir_subsidio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditarsubsidio;
    private javax.swing.JButton jButtonSalirConsultarNota6;
    private javax.swing.JButton jButtonSalirConsultarNota8;
    private javax.swing.JButton jButtonVolverConsultarNota6;
    private javax.swing.JButton jButtonVolverConsultarNota9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabelMiniSiaConsultarNota9;
    private javax.swing.JLabel jLabelTituloConsultarNota9;
    private javax.swing.JPanel jPanelEncabezadoConsultarNota9;
    private javax.swing.JPanel jPanelFondoConsultarNota8;
    private javax.swing.JPanel jPanelPiePaginaConsultarNota6;
    private javax.swing.JPanel jPanelPiePaginaConsultarNota8;
    private javax.swing.JSeparator jSeparator77;
    private javax.swing.JSeparator jSeparator78;
    // End of variables declaration//GEN-END:variables
}
