/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import Datos.*;
import Logica.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author juan manuel
 */
public class uiProt extends javax.swing.JFrame {

        ArrayList usuarios_estudiante = new ArrayList<Estudiante>(); 
        ArrayList usuarios_profesor = new ArrayList<Profesor>();
        ArrayList usuarios_papitos = new ArrayList<Papito>();
        
        
        

    /**
     * Creates new form uiProt
     */
    public uiProt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        popupMenu1 = new java.awt.PopupMenu();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        interfazEstudiante = new javax.swing.JFrame();
        jPanelFondoConsultarNota3 = new javax.swing.JPanel();
        jPanelEncabezadoConsultarNota3 = new javax.swing.JPanel();
        jLabelTituloConsultarNota3 = new javax.swing.JLabel();
        jSeparator65 = new javax.swing.JSeparator();
        jSeparator66 = new javax.swing.JSeparator();
        jLabelMiniSiaConsultarNota3 = new javax.swing.JLabel();
        jLabelResultadoConsultarNota2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        buttonNotas = new javax.swing.JButton();
        buttonHorario = new javax.swing.JButton();
        buttonSubsidios = new javax.swing.JButton();
        buttonProfesores = new javax.swing.JButton();
        buttonInforpersonal = new javax.swing.JButton();
        jLabelResultadoConsultarNota3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        buttonIncribir = new javax.swing.JButton();
        buttoncambioClave = new javax.swing.JButton();
        buttonpedirSubsidio = new javax.swing.JButton();
        jLabelResultadoConsultarNota5 = new javax.swing.JLabel();
        jPanelPiePaginaConsultarNota3 = new javax.swing.JPanel();
        jButtonSalirConsultarNota3 = new javax.swing.JButton();
        jButtonVolverConsultarNota3 = new javax.swing.JButton();
        interfazProfesor = new javax.swing.JFrame();
        mensajeBienvenida_ = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        interfazPapito = new javax.swing.JFrame();
        mensajeBienvenidaPapito = new javax.swing.JLabel();
        ingreso_fallido = new javax.swing.JDialog();
        cerrar_ventana = new java.awt.Button();
        label1 = new java.awt.Label();
        infoPersonal = new javax.swing.JFrame();
        jPanelFondoConsultarNota = new javax.swing.JPanel();
        jPanelEncabezadoConsultarNota1 = new javax.swing.JPanel();
        jLabelTituloConsultarNota1 = new javax.swing.JLabel();
        jSeparator61 = new javax.swing.JSeparator();
        jSeparator62 = new javax.swing.JSeparator();
        jLabelMiniSiaConsultarNota1 = new javax.swing.JLabel();
        jPanelPiePaginaConsultarNota1 = new javax.swing.JPanel();
        jButtonSalirConsultarNota1 = new javax.swing.JButton();
        jButtonVolverConsultarNota1 = new javax.swing.JButton();
        jLabelIngresarNombreConsultarNota1 = new javax.swing.JLabel();
        campoInfopersonal = new javax.swing.JTextField();
        pedirSubsidio = new javax.swing.JFrame();
        jPanelFondoConsultarNota4 = new javax.swing.JPanel();
        jPanelEncabezadoConsultarNota4 = new javax.swing.JPanel();
        jLabelTituloConsultarNota4 = new javax.swing.JLabel();
        jSeparator67 = new javax.swing.JSeparator();
        jSeparator68 = new javax.swing.JSeparator();
        jLabelMiniSiaConsultarNota4 = new javax.swing.JLabel();
        jPanelPiePaginaConsultarNota4 = new javax.swing.JPanel();
        jButtonSalirConsultarNota4 = new javax.swing.JButton();
        jButtonVolverConsultarNota4 = new javax.swing.JButton();
        jButtonBuscarConsultarNota2 = new javax.swing.JButton();
        opcionesDuracion = new javax.swing.JComboBox<>();
        opcionesTipo = new javax.swing.JComboBox<>();
        mostrarProfesores = new javax.swing.JFrame();
        jPanelFondoConsultarNota5 = new javax.swing.JPanel();
        jPanelEncabezadoConsultarNota5 = new javax.swing.JPanel();
        jLabelTituloConsultarNota5 = new javax.swing.JLabel();
        jSeparator69 = new javax.swing.JSeparator();
        jSeparator70 = new javax.swing.JSeparator();
        jLabelMiniSiaConsultarNota5 = new javax.swing.JLabel();
        jPanelPiePaginaConsultarNota5 = new javax.swing.JPanel();
        jButtonSalirConsultarNota5 = new javax.swing.JButton();
        jButtonVolverConsultarNota5 = new javax.swing.JButton();
        jLabelIngresarNombreConsultarNota3 = new javax.swing.JLabel();
        jTextField64 = new javax.swing.JTextField();
        cambiarClave = new javax.swing.JFrame();
        jPanelFondoConsultarNota1 = new javax.swing.JPanel();
        jPanelEncabezadoConsultarNota = new javax.swing.JPanel();
        jLabelTituloConsultarNota = new javax.swing.JLabel();
        jSeparator060 = new javax.swing.JSeparator();
        jSeparator061 = new javax.swing.JSeparator();
        jLabelMiniSiaConsultarNota = new javax.swing.JLabel();
        jPanelPiePaginaConsultarNota = new javax.swing.JPanel();
        jButtonSalirConsultarNota = new javax.swing.JButton();
        jButtonVolverConsultarNota = new javax.swing.JButton();
        jLabelIngresarNombreConsultarNota = new javax.swing.JLabel();
        buttonClaveNueva = new javax.swing.JButton();
        fieldClaveNueva = new javax.swing.JTextField();
        jLabelResultadoConsultarNota4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        usuario_espacio = new javax.swing.JTextArea();
        boton_iniciar = new javax.swing.JButton();
        clave_espacio = new javax.swing.JPasswordField();

        popupMenu1.setLabel("popupMenu1");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        interfazEstudiante.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelFondoConsultarNota3.setBackground(new java.awt.Color(205, 237, 246));
        jPanelFondoConsultarNota3.setPreferredSize(new java.awt.Dimension(410, 310));

        jPanelEncabezadoConsultarNota3.setBackground(new java.awt.Color(239, 123, 69));
        jPanelEncabezadoConsultarNota3.setPreferredSize(new java.awt.Dimension(390, 54));

        jLabelTituloConsultarNota3.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabelTituloConsultarNota3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloConsultarNota3.setText("INICIO - ESTUDIANTE");

        jSeparator66.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelMiniSiaConsultarNota3.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabelMiniSiaConsultarNota3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMiniSiaConsultarNota3.setText("MiniSia");

        javax.swing.GroupLayout jPanelEncabezadoConsultarNota3Layout = new javax.swing.GroupLayout(jPanelEncabezadoConsultarNota3);
        jPanelEncabezadoConsultarNota3.setLayout(jPanelEncabezadoConsultarNota3Layout);
        jPanelEncabezadoConsultarNota3Layout.setHorizontalGroup(
            jPanelEncabezadoConsultarNota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoConsultarNota3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEncabezadoConsultarNota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEncabezadoConsultarNota3Layout.createSequentialGroup()
                        .addComponent(jSeparator65, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelTituloConsultarNota3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMiniSiaConsultarNota3)
                .addContainerGap())
        );
        jPanelEncabezadoConsultarNota3Layout.setVerticalGroup(
            jPanelEncabezadoConsultarNota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator66, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelEncabezadoConsultarNota3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloConsultarNota3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator65, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEncabezadoConsultarNota3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMiniSiaConsultarNota3)
                .addContainerGap())
        );

        jLabelResultadoConsultarNota2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabelResultadoConsultarNota2.setText("BIENVENIDO PECHA JUNIOR ");

        jPanel8.setBackground(new java.awt.Color(94, 177, 191));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonNotas.setText("Notas");
        buttonNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNotasActionPerformed(evt);
            }
        });

        buttonHorario.setText("Horario");
        buttonHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHorarioActionPerformed(evt);
            }
        });

        buttonSubsidios.setText("Subsidios");
        buttonSubsidios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubsidiosActionPerformed(evt);
            }
        });

        buttonProfesores.setText("Profesores");
        buttonProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProfesoresActionPerformed(evt);
            }
        });

        buttonInforpersonal.setText("Info. Personal");
        buttonInforpersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInforpersonalActionPerformed(evt);
            }
        });

        jLabelResultadoConsultarNota3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabelResultadoConsultarNota3.setForeground(new java.awt.Color(240, 240, 240));
        jLabelResultadoConsultarNota3.setText("Consultar:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSubsidios, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonInforpersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                    .addComponent(buttonHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelResultadoConsultarNota3)
                .addGap(48, 48, 48))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelResultadoConsultarNota3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonNotas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSubsidios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonProfesores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonInforpersonal)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(94, 177, 191));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonIncribir.setText("Inscribir materias");
        buttonIncribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIncribirActionPerformed(evt);
            }
        });

        buttoncambioClave.setText("Cambiar clave");
        buttoncambioClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncambioClaveActionPerformed(evt);
            }
        });

        buttonpedirSubsidio.setText("Pedir subsidio");
        buttonpedirSubsidio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpedirSubsidioActionPerformed(evt);
            }
        });

        jLabelResultadoConsultarNota5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabelResultadoConsultarNota5.setForeground(new java.awt.Color(240, 240, 240));
        jLabelResultadoConsultarNota5.setText("Asignaciones:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonIncribir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttoncambioClave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonpedirSubsidio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabelResultadoConsultarNota5)))
                .addGap(26, 26, 26))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelResultadoConsultarNota5)
                .addGap(18, 18, 18)
                .addComponent(buttonIncribir)
                .addGap(18, 18, 18)
                .addComponent(buttoncambioClave)
                .addGap(18, 18, 18)
                .addComponent(buttonpedirSubsidio)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanelPiePaginaConsultarNota3.setBackground(new java.awt.Color(239, 123, 69));
        jPanelPiePaginaConsultarNota3.setPreferredSize(new java.awt.Dimension(142, 47));

        jButtonSalirConsultarNota3.setText("SALIR");
        jButtonSalirConsultarNota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirConsultarNota3ActionPerformed(evt);
            }
        });

        jButtonVolverConsultarNota3.setText("VOLVER");
        jButtonVolverConsultarNota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverConsultarNota3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPiePaginaConsultarNota3Layout = new javax.swing.GroupLayout(jPanelPiePaginaConsultarNota3);
        jPanelPiePaginaConsultarNota3.setLayout(jPanelPiePaginaConsultarNota3Layout);
        jPanelPiePaginaConsultarNota3Layout.setHorizontalGroup(
            jPanelPiePaginaConsultarNota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarNota3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolverConsultarNota3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalirConsultarNota3)
                .addGap(18, 18, 18))
        );
        jPanelPiePaginaConsultarNota3Layout.setVerticalGroup(
            jPanelPiePaginaConsultarNota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarNota3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelPiePaginaConsultarNota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalirConsultarNota3)
                    .addComponent(jButtonVolverConsultarNota3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelFondoConsultarNota3Layout = new javax.swing.GroupLayout(jPanelFondoConsultarNota3);
        jPanelFondoConsultarNota3.setLayout(jPanelFondoConsultarNota3Layout);
        jPanelFondoConsultarNota3Layout.setHorizontalGroup(
            jPanelFondoConsultarNota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEncabezadoConsultarNota3, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
            .addGroup(jPanelFondoConsultarNota3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFondoConsultarNota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoConsultarNota3Layout.createSequentialGroup()
                        .addComponent(jLabelResultadoConsultarNota2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelFondoConsultarNota3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))))
            .addComponent(jPanelPiePaginaConsultarNota3, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );
        jPanelFondoConsultarNota3Layout.setVerticalGroup(
            jPanelFondoConsultarNota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoConsultarNota3Layout.createSequentialGroup()
                .addComponent(jPanelEncabezadoConsultarNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelResultadoConsultarNota2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFondoConsultarNota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPiePaginaConsultarNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout interfazEstudianteLayout = new javax.swing.GroupLayout(interfazEstudiante.getContentPane());
        interfazEstudiante.getContentPane().setLayout(interfazEstudianteLayout);
        interfazEstudianteLayout.setHorizontalGroup(
            interfazEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoConsultarNota3, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );
        interfazEstudianteLayout.setVerticalGroup(
            interfazEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoConsultarNota3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        interfazEstudiante.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout interfazProfesorLayout = new javax.swing.GroupLayout(interfazProfesor.getContentPane());
        interfazProfesor.getContentPane().setLayout(interfazProfesorLayout);
        interfazProfesorLayout.setHorizontalGroup(
            interfazProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interfazProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(mensajeBienvenida_, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        interfazProfesorLayout.setVerticalGroup(
            interfazProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interfazProfesorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(interfazProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(interfazProfesorLayout.createSequentialGroup()
                        .addComponent(mensajeBienvenida_, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 225, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout interfazPapitoLayout = new javax.swing.GroupLayout(interfazPapito.getContentPane());
        interfazPapito.getContentPane().setLayout(interfazPapitoLayout);
        interfazPapitoLayout.setHorizontalGroup(
            interfazPapitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interfazPapitoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(mensajeBienvenidaPapito, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        interfazPapitoLayout.setVerticalGroup(
            interfazPapitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interfazPapitoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(mensajeBienvenidaPapito, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        cerrar_ventana.setLabel("Aceptar");
        cerrar_ventana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar_ventanaActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Lo siento, has ingresado incorrectamente los datos, vuelve a intentarlo.");

        javax.swing.GroupLayout ingreso_fallidoLayout = new javax.swing.GroupLayout(ingreso_fallido.getContentPane());
        ingreso_fallido.getContentPane().setLayout(ingreso_fallidoLayout);
        ingreso_fallidoLayout.setHorizontalGroup(
            ingreso_fallidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingreso_fallidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ingreso_fallidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cerrar_ventana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
        );
        ingreso_fallidoLayout.setVerticalGroup(
            ingreso_fallidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingreso_fallidoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(cerrar_ventana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        infoPersonal.setAutoRequestFocus(false);
        infoPersonal.setBackground(new java.awt.Color(192, 30, 40));

        jPanelFondoConsultarNota.setBackground(new java.awt.Color(205, 237, 246));
        jPanelFondoConsultarNota.setPreferredSize(new java.awt.Dimension(410, 310));

        jPanelEncabezadoConsultarNota1.setBackground(new java.awt.Color(239, 123, 69));
        jPanelEncabezadoConsultarNota1.setPreferredSize(new java.awt.Dimension(390, 54));

        jLabelTituloConsultarNota1.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabelTituloConsultarNota1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloConsultarNota1.setText("CONSULTAR INFORMACIÓN ");

        jSeparator62.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelMiniSiaConsultarNota1.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabelMiniSiaConsultarNota1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMiniSiaConsultarNota1.setText("MiniSia");

        javax.swing.GroupLayout jPanelEncabezadoConsultarNota1Layout = new javax.swing.GroupLayout(jPanelEncabezadoConsultarNota1);
        jPanelEncabezadoConsultarNota1.setLayout(jPanelEncabezadoConsultarNota1Layout);
        jPanelEncabezadoConsultarNota1Layout.setHorizontalGroup(
            jPanelEncabezadoConsultarNota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoConsultarNota1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEncabezadoConsultarNota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator61, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTituloConsultarNota1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator62, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMiniSiaConsultarNota1)
                .addGap(27, 27, 27))
        );
        jPanelEncabezadoConsultarNota1Layout.setVerticalGroup(
            jPanelEncabezadoConsultarNota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator62, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelEncabezadoConsultarNota1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloConsultarNota1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator61, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEncabezadoConsultarNota1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMiniSiaConsultarNota1)
                .addContainerGap())
        );

        jPanelPiePaginaConsultarNota1.setBackground(new java.awt.Color(239, 123, 69));
        jPanelPiePaginaConsultarNota1.setPreferredSize(new java.awt.Dimension(142, 47));

        jButtonSalirConsultarNota1.setText("SALIR");
        jButtonSalirConsultarNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirConsultarNota1ActionPerformed(evt);
            }
        });

        jButtonVolverConsultarNota1.setText("VOLVER");
        jButtonVolverConsultarNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverConsultarNota1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPiePaginaConsultarNota1Layout = new javax.swing.GroupLayout(jPanelPiePaginaConsultarNota1);
        jPanelPiePaginaConsultarNota1.setLayout(jPanelPiePaginaConsultarNota1Layout);
        jPanelPiePaginaConsultarNota1Layout.setHorizontalGroup(
            jPanelPiePaginaConsultarNota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarNota1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolverConsultarNota1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalirConsultarNota1)
                .addGap(18, 18, 18))
        );
        jPanelPiePaginaConsultarNota1Layout.setVerticalGroup(
            jPanelPiePaginaConsultarNota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarNota1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelPiePaginaConsultarNota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalirConsultarNota1)
                    .addComponent(jButtonVolverConsultarNota1))
                .addContainerGap())
        );

        jLabelIngresarNombreConsultarNota1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabelIngresarNombreConsultarNota1.setText("Esto es lo que el sistema sabe de ti:");

        javax.swing.GroupLayout jPanelFondoConsultarNotaLayout = new javax.swing.GroupLayout(jPanelFondoConsultarNota);
        jPanelFondoConsultarNota.setLayout(jPanelFondoConsultarNotaLayout);
        jPanelFondoConsultarNotaLayout.setHorizontalGroup(
            jPanelFondoConsultarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEncabezadoConsultarNota1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addComponent(jPanelPiePaginaConsultarNota1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addGroup(jPanelFondoConsultarNotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIngresarNombreConsultarNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoConsultarNotaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campoInfopersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanelFondoConsultarNotaLayout.setVerticalGroup(
            jPanelFondoConsultarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoConsultarNotaLayout.createSequentialGroup()
                .addComponent(jPanelEncabezadoConsultarNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelIngresarNombreConsultarNota1)
                .addGap(11, 11, 11)
                .addComponent(campoInfopersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelPiePaginaConsultarNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout infoPersonalLayout = new javax.swing.GroupLayout(infoPersonal.getContentPane());
        infoPersonal.getContentPane().setLayout(infoPersonalLayout);
        infoPersonalLayout.setHorizontalGroup(
            infoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoConsultarNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        infoPersonalLayout.setVerticalGroup(
            infoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPersonalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelFondoConsultarNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelFondoConsultarNota4.setBackground(new java.awt.Color(205, 237, 246));
        jPanelFondoConsultarNota4.setPreferredSize(new java.awt.Dimension(410, 310));

        jPanelEncabezadoConsultarNota4.setBackground(new java.awt.Color(239, 123, 69));
        jPanelEncabezadoConsultarNota4.setPreferredSize(new java.awt.Dimension(390, 54));

        jLabelTituloConsultarNota4.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabelTituloConsultarNota4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloConsultarNota4.setText("PEDIR SUBSIDIO");

        jSeparator68.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelMiniSiaConsultarNota4.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabelMiniSiaConsultarNota4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMiniSiaConsultarNota4.setText("MiniSia");

        javax.swing.GroupLayout jPanelEncabezadoConsultarNota4Layout = new javax.swing.GroupLayout(jPanelEncabezadoConsultarNota4);
        jPanelEncabezadoConsultarNota4.setLayout(jPanelEncabezadoConsultarNota4Layout);
        jPanelEncabezadoConsultarNota4Layout.setHorizontalGroup(
            jPanelEncabezadoConsultarNota4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoConsultarNota4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEncabezadoConsultarNota4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator67, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTituloConsultarNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator68, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMiniSiaConsultarNota4)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelEncabezadoConsultarNota4Layout.setVerticalGroup(
            jPanelEncabezadoConsultarNota4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator68, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelEncabezadoConsultarNota4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloConsultarNota4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator67, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEncabezadoConsultarNota4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMiniSiaConsultarNota4)
                .addContainerGap())
        );

        jPanelPiePaginaConsultarNota4.setBackground(new java.awt.Color(239, 123, 69));
        jPanelPiePaginaConsultarNota4.setPreferredSize(new java.awt.Dimension(142, 47));

        jButtonSalirConsultarNota4.setText("SALIR");
        jButtonSalirConsultarNota4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirConsultarNota4ActionPerformed(evt);
            }
        });

        jButtonVolverConsultarNota4.setText("VOLVER");
        jButtonVolverConsultarNota4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverConsultarNota4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPiePaginaConsultarNota4Layout = new javax.swing.GroupLayout(jPanelPiePaginaConsultarNota4);
        jPanelPiePaginaConsultarNota4.setLayout(jPanelPiePaginaConsultarNota4Layout);
        jPanelPiePaginaConsultarNota4Layout.setHorizontalGroup(
            jPanelPiePaginaConsultarNota4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarNota4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolverConsultarNota4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalirConsultarNota4)
                .addGap(18, 18, 18))
        );
        jPanelPiePaginaConsultarNota4Layout.setVerticalGroup(
            jPanelPiePaginaConsultarNota4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarNota4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelPiePaginaConsultarNota4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalirConsultarNota4)
                    .addComponent(jButtonVolverConsultarNota4))
                .addContainerGap())
        );

        jButtonBuscarConsultarNota2.setText("CONFIRMAR SUBSIDIO");
        jButtonBuscarConsultarNota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarConsultarNota2ActionPerformed(evt);
            }
        });

        opcionesDuracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        opcionesDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesDuracionActionPerformed(evt);
            }
        });

        opcionesTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        opcionesTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoConsultarNota4Layout = new javax.swing.GroupLayout(jPanelFondoConsultarNota4);
        jPanelFondoConsultarNota4.setLayout(jPanelFondoConsultarNota4Layout);
        jPanelFondoConsultarNota4Layout.setHorizontalGroup(
            jPanelFondoConsultarNota4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEncabezadoConsultarNota4, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addComponent(jPanelPiePaginaConsultarNota4, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoConsultarNota4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(opcionesTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opcionesDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanelFondoConsultarNota4Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButtonBuscarConsultarNota2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFondoConsultarNota4Layout.setVerticalGroup(
            jPanelFondoConsultarNota4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoConsultarNota4Layout.createSequentialGroup()
                .addComponent(jPanelEncabezadoConsultarNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanelFondoConsultarNota4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionesDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcionesTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButtonBuscarConsultarNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelPiePaginaConsultarNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pedirSubsidioLayout = new javax.swing.GroupLayout(pedirSubsidio.getContentPane());
        pedirSubsidio.getContentPane().setLayout(pedirSubsidioLayout);
        pedirSubsidioLayout.setHorizontalGroup(
            pedirSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoConsultarNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pedirSubsidioLayout.setVerticalGroup(
            pedirSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoConsultarNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelFondoConsultarNota5.setBackground(new java.awt.Color(205, 237, 246));
        jPanelFondoConsultarNota5.setPreferredSize(new java.awt.Dimension(410, 310));

        jPanelEncabezadoConsultarNota5.setBackground(new java.awt.Color(239, 123, 69));
        jPanelEncabezadoConsultarNota5.setPreferredSize(new java.awt.Dimension(390, 54));

        jLabelTituloConsultarNota5.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabelTituloConsultarNota5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloConsultarNota5.setText("PROFESORES");

        jSeparator70.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelMiniSiaConsultarNota5.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabelMiniSiaConsultarNota5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMiniSiaConsultarNota5.setText("MiniSia");

        javax.swing.GroupLayout jPanelEncabezadoConsultarNota5Layout = new javax.swing.GroupLayout(jPanelEncabezadoConsultarNota5);
        jPanelEncabezadoConsultarNota5.setLayout(jPanelEncabezadoConsultarNota5Layout);
        jPanelEncabezadoConsultarNota5Layout.setHorizontalGroup(
            jPanelEncabezadoConsultarNota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoConsultarNota5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEncabezadoConsultarNota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator69, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTituloConsultarNota5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator70, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMiniSiaConsultarNota5)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelEncabezadoConsultarNota5Layout.setVerticalGroup(
            jPanelEncabezadoConsultarNota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator70, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelEncabezadoConsultarNota5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloConsultarNota5, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator69, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEncabezadoConsultarNota5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMiniSiaConsultarNota5)
                .addContainerGap())
        );

        jPanelPiePaginaConsultarNota5.setBackground(new java.awt.Color(239, 123, 69));
        jPanelPiePaginaConsultarNota5.setPreferredSize(new java.awt.Dimension(142, 47));

        jButtonSalirConsultarNota5.setText("SALIR");
        jButtonSalirConsultarNota5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirConsultarNota5ActionPerformed(evt);
            }
        });

        jButtonVolverConsultarNota5.setText("VOLVER");
        jButtonVolverConsultarNota5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverConsultarNota5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPiePaginaConsultarNota5Layout = new javax.swing.GroupLayout(jPanelPiePaginaConsultarNota5);
        jPanelPiePaginaConsultarNota5.setLayout(jPanelPiePaginaConsultarNota5Layout);
        jPanelPiePaginaConsultarNota5Layout.setHorizontalGroup(
            jPanelPiePaginaConsultarNota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarNota5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolverConsultarNota5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalirConsultarNota5)
                .addGap(18, 18, 18))
        );
        jPanelPiePaginaConsultarNota5Layout.setVerticalGroup(
            jPanelPiePaginaConsultarNota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarNota5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelPiePaginaConsultarNota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalirConsultarNota5)
                    .addComponent(jButtonVolverConsultarNota5))
                .addContainerGap())
        );

        jLabelIngresarNombreConsultarNota3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabelIngresarNombreConsultarNota3.setText("Estos son tus profesores:");

        javax.swing.GroupLayout jPanelFondoConsultarNota5Layout = new javax.swing.GroupLayout(jPanelFondoConsultarNota5);
        jPanelFondoConsultarNota5.setLayout(jPanelFondoConsultarNota5Layout);
        jPanelFondoConsultarNota5Layout.setHorizontalGroup(
            jPanelFondoConsultarNota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEncabezadoConsultarNota5, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addComponent(jPanelPiePaginaConsultarNota5, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addGroup(jPanelFondoConsultarNota5Layout.createSequentialGroup()
                .addGroup(jPanelFondoConsultarNota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoConsultarNota5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelIngresarNombreConsultarNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFondoConsultarNota5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jTextField64, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelFondoConsultarNota5Layout.setVerticalGroup(
            jPanelFondoConsultarNota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoConsultarNota5Layout.createSequentialGroup()
                .addComponent(jPanelEncabezadoConsultarNota5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelIngresarNombreConsultarNota3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField64, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelPiePaginaConsultarNota5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout mostrarProfesoresLayout = new javax.swing.GroupLayout(mostrarProfesores.getContentPane());
        mostrarProfesores.getContentPane().setLayout(mostrarProfesoresLayout);
        mostrarProfesoresLayout.setHorizontalGroup(
            mostrarProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(mostrarProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mostrarProfesoresLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelFondoConsultarNota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        mostrarProfesoresLayout.setVerticalGroup(
            mostrarProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(mostrarProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mostrarProfesoresLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelFondoConsultarNota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelFondoConsultarNota1.setBackground(new java.awt.Color(205, 237, 246));
        jPanelFondoConsultarNota1.setPreferredSize(new java.awt.Dimension(410, 310));

        jPanelEncabezadoConsultarNota.setBackground(new java.awt.Color(239, 123, 69));
        jPanelEncabezadoConsultarNota.setPreferredSize(new java.awt.Dimension(390, 54));

        jLabelTituloConsultarNota.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabelTituloConsultarNota.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloConsultarNota.setText("CAMBIAR CLAVE");

        jSeparator061.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelMiniSiaConsultarNota.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabelMiniSiaConsultarNota.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMiniSiaConsultarNota.setText("MiniSia");

        javax.swing.GroupLayout jPanelEncabezadoConsultarNotaLayout = new javax.swing.GroupLayout(jPanelEncabezadoConsultarNota);
        jPanelEncabezadoConsultarNota.setLayout(jPanelEncabezadoConsultarNotaLayout);
        jPanelEncabezadoConsultarNotaLayout.setHorizontalGroup(
            jPanelEncabezadoConsultarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoConsultarNotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEncabezadoConsultarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator060, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTituloConsultarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator061, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMiniSiaConsultarNota)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelEncabezadoConsultarNotaLayout.setVerticalGroup(
            jPanelEncabezadoConsultarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator061, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelEncabezadoConsultarNotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloConsultarNota, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator060, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEncabezadoConsultarNotaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMiniSiaConsultarNota)
                .addContainerGap())
        );

        jPanelPiePaginaConsultarNota.setBackground(new java.awt.Color(239, 123, 69));
        jPanelPiePaginaConsultarNota.setPreferredSize(new java.awt.Dimension(142, 47));

        jButtonSalirConsultarNota.setText("SALIR");
        jButtonSalirConsultarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirConsultarNotaActionPerformed(evt);
            }
        });

        jButtonVolverConsultarNota.setText("VOLVER");
        jButtonVolverConsultarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverConsultarNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPiePaginaConsultarNotaLayout = new javax.swing.GroupLayout(jPanelPiePaginaConsultarNota);
        jPanelPiePaginaConsultarNota.setLayout(jPanelPiePaginaConsultarNotaLayout);
        jPanelPiePaginaConsultarNotaLayout.setHorizontalGroup(
            jPanelPiePaginaConsultarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarNotaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolverConsultarNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalirConsultarNota)
                .addGap(18, 18, 18))
        );
        jPanelPiePaginaConsultarNotaLayout.setVerticalGroup(
            jPanelPiePaginaConsultarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPiePaginaConsultarNotaLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelPiePaginaConsultarNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalirConsultarNota)
                    .addComponent(jButtonVolverConsultarNota))
                .addContainerGap())
        );

        jLabelIngresarNombreConsultarNota.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabelIngresarNombreConsultarNota.setText("Ingrese una clave nueva:");

        buttonClaveNueva.setText("CAMBIAR");
        buttonClaveNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClaveNuevaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoConsultarNota1Layout = new javax.swing.GroupLayout(jPanelFondoConsultarNota1);
        jPanelFondoConsultarNota1.setLayout(jPanelFondoConsultarNota1Layout);
        jPanelFondoConsultarNota1Layout.setHorizontalGroup(
            jPanelFondoConsultarNota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEncabezadoConsultarNota, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addComponent(jPanelPiePaginaConsultarNota, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addGroup(jPanelFondoConsultarNota1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFondoConsultarNota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoConsultarNota1Layout.createSequentialGroup()
                        .addComponent(fieldClaveNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(buttonClaveNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelIngresarNombreConsultarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelFondoConsultarNota1Layout.setVerticalGroup(
            jPanelFondoConsultarNota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoConsultarNota1Layout.createSequentialGroup()
                .addComponent(jPanelEncabezadoConsultarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelIngresarNombreConsultarNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFondoConsultarNota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldClaveNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClaveNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jPanelPiePaginaConsultarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout cambiarClaveLayout = new javax.swing.GroupLayout(cambiarClave.getContentPane());
        cambiarClave.getContentPane().setLayout(cambiarClaveLayout);
        cambiarClaveLayout.setHorizontalGroup(
            cambiarClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoConsultarNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        cambiarClaveLayout.setVerticalGroup(
            cambiarClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoConsultarNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabelResultadoConsultarNota4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabelResultadoConsultarNota4.setText("Consultar:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MinisiaV1");
        setBackground(new java.awt.Color(255, 255, 204));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 204, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("BIENVENIDO AL MiniSIA ");
        jTextArea1.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setViewportView(jTextArea1);

        button1.setActionCommand("ingresarUsuario");
        button1.setLabel("Ingresar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña");

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        usuario_espacio.setColumns(20);
        usuario_espacio.setRows(5);
        jScrollPane4.setViewportView(usuario_espacio);

        boton_iniciar.setText("iniciar");
        boton_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_iniciarActionPerformed(evt);
            }
        });

        clave_espacio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clave_espacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clave_espacioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(clave_espacio, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_iniciar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clave_espacio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(boton_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        boton_iniciar.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
         
                //Generando objetos para probar el sistema:
     
        // Prueba
        
        String id_usuario_ = usuario_espacio.getText();
         int id_usuario = Integer.parseInt(id_usuario_);
         String clave_usuario = clave_espacio.getText();
         
            if( id_usuario <= 200){
            //busca entre profesores
      
            buscarProfesor(usuarios_profesor, id_usuario, clave_usuario );
          
        }
        
        if(id_usuario > 200 && id_usuario < 500){
            //busca entre papito
            buscarPapito(usuarios_papitos, id_usuario, clave_usuario );
        }
        
        if(id_usuario >=600 && id_usuario <= 800){
            //busca entre estudianto
            buscarEstudiante(usuarios_estudiante, id_usuario, clave_usuario );
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void boton_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_iniciarActionPerformed
        iniciarSia();
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_iniciarActionPerformed

    private void cerrar_ventanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar_ventanaActionPerformed
        ingreso_fallido.setVisible(false);
    }//GEN-LAST:event_cerrar_ventanaActionPerformed

    private void clave_espacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clave_espacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clave_espacioActionPerformed

    private void buttonClaveNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClaveNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClaveNuevaActionPerformed

    private void jButtonVolverConsultarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverConsultarNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverConsultarNotaActionPerformed

    private void jButtonSalirConsultarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirConsultarNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirConsultarNotaActionPerformed

    private void buttonNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNotasActionPerformed

    private void jButtonVolverConsultarNota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverConsultarNota3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverConsultarNota3ActionPerformed

    private void jButtonSalirConsultarNota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirConsultarNota3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirConsultarNota3ActionPerformed

    private void buttonHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonHorarioActionPerformed

    private void buttonSubsidiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubsidiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSubsidiosActionPerformed

    private void buttonProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProfesoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonProfesoresActionPerformed

    private void buttonInforpersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInforpersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonInforpersonalActionPerformed

    private void buttonIncribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIncribirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonIncribirActionPerformed

    private void buttoncambioClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncambioClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttoncambioClaveActionPerformed

    private void buttonpedirSubsidioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpedirSubsidioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonpedirSubsidioActionPerformed

    private void jButtonBuscarConsultarNota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarConsultarNota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarConsultarNota2ActionPerformed

    private void jButtonVolverConsultarNota4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverConsultarNota4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverConsultarNota4ActionPerformed

    private void jButtonSalirConsultarNota4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirConsultarNota4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirConsultarNota4ActionPerformed

    private void opcionesDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesDuracionActionPerformed

    private void opcionesTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesTipoActionPerformed

    private void jButtonSalirConsultarNota5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirConsultarNota5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirConsultarNota5ActionPerformed

    private void jButtonVolverConsultarNota5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverConsultarNota5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverConsultarNota5ActionPerformed

    private void jButtonSalirConsultarNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirConsultarNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirConsultarNota1ActionPerformed

    private void jButtonVolverConsultarNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverConsultarNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverConsultarNota1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    
   
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uiProt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uiProt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uiProt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uiProt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uiProt().setVisible(true);
            }
        });
    }
    
    //METODOS PARA EL LOGIN
      public  void buscarProfesor(ArrayList<Profesor> lista, int id, String clave){
        for(Profesor buscando: lista){
            if(buscando.getID()== id && buscando.getClave().equals(clave)){
                System.out.println("Bienvenido " + buscando.getNombre());
                //Se llama a metodo que le muestra la interfaz al profesor.
                interfazExitosa(buscando);
               
            }
        }
        //System.out.println("Id y/o clave incorrectos. Vuelva a intentar");
        //ingreso_fallido.setVisible(true);
        //System.exit(1);
    }
    
     public  void buscarPapito(ArrayList<Papito> lista, int id, String clave){
        for(Papito buscando: lista){
            if(buscando.getID()== id && buscando.getClave().equals(clave)){
                System.out.println("Bienvenido " + buscando.getNombre());
                //Se llama a metodo que le muestra la interfaz al papito.
                interfazExitosa(buscando);
            }
        }
        
        //System.out.println("Id y/o clave incorrectos. Vuelva a intentar");
        ingreso_fallido.setVisible(true);
        //Hay un problema, y es con el login, si entras te sale la opción de volver a intentarlo
        //System.exit(1);
    }
     
      public  void buscarEstudiante(ArrayList<Estudiante> lista, int id, String clave){
        for(Estudiante buscando: lista){
            if(buscando.getID()== id && buscando.getClave().equals(clave)){
                System.out.println("Bienvenido " + buscando.getNombre());
   
                //Se llama a metodo que le muestra la interfaz al profesor.
                interfazExitosa(buscando);
                 
             
            }
        }
        
        //System.exit(1);
    }
      //-------------------
      //METODO PARA "INICIAR" SISTEMA
    
    public void iniciarSia(){
             for(int i= 0; i< 10; i++){
            usuarios_papitos.add(new Papito());
        }
        
        for(int j=0; j<5; j++){
            usuarios_profesor.add(new Profesor());
        }
        
        for(int k=0; k<20; k++){
            usuarios_estudiante.add(new Estudiante());
        }
    
        //
        Estudiante est_prueb1 = (Estudiante) usuarios_estudiante.get(15);
        Profesor est_prueb2 = (Profesor) usuarios_profesor.get(1);
        Papito est_prueb3 = (Papito) usuarios_papitos.get(2);
        est_prueb1.setNombre("Juan Cortes");
        est_prueb2.setNombre("Arcenio Pecha");
        est_prueb3.setNombre("Padre Cardenas");
        
        int id_1 = est_prueb1.getID();
        String clave_1 = est_prueb1.getClave();
        
        int id_2 = est_prueb2.getID();
        String clave_2 = est_prueb2.getClave();
        
        int id_3 = est_prueb3.getID();
        String clave_3 = est_prueb3.getClave();
        
        
        System.out.println("Datos para prueba "+ est_prueb1.getNombre() +"\n id: " +id_1  + "\n clave: " + clave_1);
        System.out.println("Datos para prueba "+ est_prueb2.getNombre() +"\n id: " +id_2  + "\n clave: " + clave_2);
        System.out.println("Datos para prueba "+ est_prueb3.getNombre() +"\n id: " +id_3  + "\n clave: " + clave_3);
    }
    
    public void interfazFallida(){
        ingreso_fallido.setTitle("Vuelve a intentarlo");
         ingreso_fallido.locate(500, 500);
        ingreso_fallido.setSize(400,300);
        
    }
    
    public void interfazExitosa( Estudiante encontrado){
        jInternalFrame1.setVisible(false);
        interfazEstudiante.setAlwaysOnTop(true);
         interfazEstudiante.locate(500, 500);
        interfazEstudiante.setVisible(true);
        interfazEstudiante.setTitle("Interfaz Estudiante");
        mensajeBienvenida.setText("Bienvenido " + encontrado.getNombre());
        //mensajeBienvenida.setVisible(false);
        interfazEstudiante.setSize(700, 400);
        
    }
    
    public void interfazExitosa(Profesor encontrado){
        mensajeBienvenida_.setVisible(true);
        mensajeBienvenida_.setText("Bienvenido " + encontrado.getNombre());
        interfazProfesor.setAlwaysOnTop(true);
        interfazProfesor.locate(500, 500);
        interfazProfesor.setVisible(true);
        interfazProfesor.setTitle("Interfaz Profesor");
        
        interfazProfesor.setSize(700, 400);
        
    }
    
    public void interfazExitosa(Papito encontrado){
          mensajeBienvenidaPapito.setVisible(true);
       mensajeBienvenidaPapito.setText("Bienvenido " + encontrado.getNombre());
       interfazPapito.setAlwaysOnTop(true);
       interfazPapito.locate(500, 500);
        interfazPapito.setVisible(true);
        interfazPapito.setTitle("Interfaz Papito");
        
        interfazPapito.setSize(700, 400);
    }

    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_iniciar;
    private java.awt.Button button1;
    private javax.swing.JButton buttonClaveNueva;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonHorario;
    private javax.swing.JButton buttonIncribir;
    private javax.swing.JButton buttonInforpersonal;
    private javax.swing.JButton buttonNotas;
    private javax.swing.JButton buttonProfesores;
    private javax.swing.JButton buttonSubsidios;
    private javax.swing.JButton buttoncambioClave;
    private javax.swing.JButton buttonpedirSubsidio;
    private javax.swing.JFrame cambiarClave;
    private javax.swing.JTextField campoInfopersonal;
    private java.awt.Button cerrar_ventana;
    private javax.swing.JPasswordField clave_espacio;
    private javax.swing.JTextField fieldClaveNueva;
    private javax.swing.JFrame infoPersonal;
    private javax.swing.JDialog ingreso_fallido;
    private javax.swing.JFrame interfazEstudiante;
    private javax.swing.JFrame interfazPapito;
    private javax.swing.JFrame interfazProfesor;
    private javax.swing.JButton jButtonBuscarConsultarNota2;
    private javax.swing.JButton jButtonSalirConsultarNota;
    private javax.swing.JButton jButtonSalirConsultarNota1;
    private javax.swing.JButton jButtonSalirConsultarNota3;
    private javax.swing.JButton jButtonSalirConsultarNota4;
    private javax.swing.JButton jButtonSalirConsultarNota5;
    private javax.swing.JButton jButtonVolverConsultarNota;
    private javax.swing.JButton jButtonVolverConsultarNota1;
    private javax.swing.JButton jButtonVolverConsultarNota3;
    private javax.swing.JButton jButtonVolverConsultarNota4;
    private javax.swing.JButton jButtonVolverConsultarNota5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelIngresarNombreConsultarNota;
    private javax.swing.JLabel jLabelIngresarNombreConsultarNota1;
    private javax.swing.JLabel jLabelIngresarNombreConsultarNota3;
    private javax.swing.JLabel jLabelMiniSiaConsultarNota;
    private javax.swing.JLabel jLabelMiniSiaConsultarNota1;
    private javax.swing.JLabel jLabelMiniSiaConsultarNota3;
    private javax.swing.JLabel jLabelMiniSiaConsultarNota4;
    private javax.swing.JLabel jLabelMiniSiaConsultarNota5;
    private javax.swing.JLabel jLabelResultadoConsultarNota2;
    private javax.swing.JLabel jLabelResultadoConsultarNota3;
    private javax.swing.JLabel jLabelResultadoConsultarNota4;
    private javax.swing.JLabel jLabelResultadoConsultarNota5;
    private javax.swing.JLabel jLabelTituloConsultarNota;
    private javax.swing.JLabel jLabelTituloConsultarNota1;
    private javax.swing.JLabel jLabelTituloConsultarNota3;
    private javax.swing.JLabel jLabelTituloConsultarNota4;
    private javax.swing.JLabel jLabelTituloConsultarNota5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelEncabezadoConsultarNota;
    private javax.swing.JPanel jPanelEncabezadoConsultarNota1;
    private javax.swing.JPanel jPanelEncabezadoConsultarNota3;
    private javax.swing.JPanel jPanelEncabezadoConsultarNota4;
    private javax.swing.JPanel jPanelEncabezadoConsultarNota5;
    private javax.swing.JPanel jPanelFondoConsultarNota;
    private javax.swing.JPanel jPanelFondoConsultarNota1;
    private javax.swing.JPanel jPanelFondoConsultarNota3;
    private javax.swing.JPanel jPanelFondoConsultarNota4;
    private javax.swing.JPanel jPanelFondoConsultarNota5;
    private javax.swing.JPanel jPanelPiePaginaConsultarNota;
    private javax.swing.JPanel jPanelPiePaginaConsultarNota1;
    private javax.swing.JPanel jPanelPiePaginaConsultarNota3;
    private javax.swing.JPanel jPanelPiePaginaConsultarNota4;
    private javax.swing.JPanel jPanelPiePaginaConsultarNota5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator060;
    private javax.swing.JSeparator jSeparator061;
    private javax.swing.JSeparator jSeparator61;
    private javax.swing.JSeparator jSeparator62;
    private javax.swing.JSeparator jSeparator65;
    private javax.swing.JSeparator jSeparator66;
    private javax.swing.JSeparator jSeparator67;
    private javax.swing.JSeparator jSeparator68;
    private javax.swing.JSeparator jSeparator69;
    private javax.swing.JSeparator jSeparator70;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField64;
    private java.awt.Label label1;
    private javax.swing.JLabel mensajeBienvenidaPapito;
    private javax.swing.JLabel mensajeBienvenida_;
    private javax.swing.JFrame mostrarProfesores;
    private javax.swing.JComboBox<String> opcionesDuracion;
    private javax.swing.JComboBox<String> opcionesTipo;
    private javax.swing.JFrame pedirSubsidio;
    private java.awt.PopupMenu popupMenu1;
    public javax.swing.JTextArea usuario_espacio;
    // End of variables declaration//GEN-END:variables
}
